// Code generated by notifygen. DO NOT EDIT.
// Шаблон sessions-revoked, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона sessions-revoked (экспорт для стражей вызывающего, УК70).
const (
	SessionsRevokedRecipientPerDay = 10
)

// SessionsRevokedAttrs — атрибуты шаблона sessions-revoked. Нулевое поле optional — «не задан».
type SessionsRevokedAttrs struct {
	To         string
	OccurredAt time.Time
	UserId     string
}

var sessionsRevokedDesc = feed.TemplateDesc{
	Name:      "sessions-revoked",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "user_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendSessionsRevoked ставит письмо шаблона sessions-revoked в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendSessionsRevoked(ctx context.Context, tx pgx.Tx, a SessionsRevokedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 2)}
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["user_id"] = a.UserId
	return feed.PutID(ctx, tx, sessionsRevokedDesc, a.To, values)
}
