// Code generated by notifygen. DO NOT EDIT.
// Шаблон sa-key-issued, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона sa-key-issued (экспорт для стражей вызывающего, УК70).
const (
	SaKeyIssuedRecipientPerDay = 10
)

// SaKeyIssuedAttrs — атрибуты шаблона sa-key-issued. Нулевое поле optional — «не задан».
type SaKeyIssuedAttrs struct {
	To               string
	AccountId        string
	KeyId            string
	OccurredAt       time.Time
	ServiceAccountId string
}

var saKeyIssuedDesc = feed.TemplateDesc{
	Name:      "sa-key-issued",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "account_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "key_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "service_account_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendSaKeyIssued ставит письмо шаблона sa-key-issued в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendSaKeyIssued(ctx context.Context, tx pgx.Tx, a SaKeyIssuedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 4)}
	values.Attrs["account_id"] = a.AccountId
	values.Attrs["key_id"] = a.KeyId
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["service_account_id"] = a.ServiceAccountId
	return feed.PutID(ctx, tx, saKeyIssuedDesc, a.To, values)
}
