// Code generated by notifygen. DO NOT EDIT.
// Шаблон access-key-changed, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона access-key-changed (экспорт для стражей вызывающего, УК70).
const (
	AccessKeyChangedRecipientPerDay = 10
)

// AccessKeyChangedAttrs — атрибуты шаблона access-key-changed. Нулевое поле optional — «не задан».
type AccessKeyChangedAttrs struct {
	To          string
	AccessKeyId string
	Change      string
	OccurredAt  time.Time
}

var accessKeyChangedDesc = feed.TemplateDesc{
	Name:      "access-key-changed",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "access_key_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "change", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendAccessKeyChanged ставит письмо шаблона access-key-changed в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendAccessKeyChanged(ctx context.Context, tx pgx.Tx, a AccessKeyChangedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 3)}
	values.Attrs["access_key_id"] = a.AccessKeyId
	values.Attrs["change"] = a.Change
	values.Attrs["occurred_at"] = a.OccurredAt
	return feed.PutID(ctx, tx, accessKeyChangedDesc, a.To, values)
}
