// Code generated by notifygen. DO NOT EDIT.
// Шаблон second-factor-changed, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона second-factor-changed (экспорт для стражей вызывающего, УК70).
const (
	SecondFactorChangedRecipientPerDay = 10
)

// SecondFactorChangedAttrs — атрибуты шаблона second-factor-changed. Нулевое поле optional — «не задан».
type SecondFactorChangedAttrs struct {
	To         string
	Change     string
	OccurredAt time.Time
	UserId     string
}

var secondFactorChangedDesc = feed.TemplateDesc{
	Name:      "second-factor-changed",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "change", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "user_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendSecondFactorChanged ставит письмо шаблона second-factor-changed в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendSecondFactorChanged(ctx context.Context, tx pgx.Tx, a SecondFactorChangedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 3)}
	values.Attrs["change"] = a.Change
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["user_id"] = a.UserId
	return feed.PutID(ctx, tx, secondFactorChangedDesc, a.To, values)
}
