// Code generated by notifygen. DO NOT EDIT.
// Шаблон new-device-login, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона new-device-login (экспорт для стражей вызывающего, УК70).
const (
	NewDeviceLoginRecipientPerDay = 10
)

// NewDeviceLoginAttrs — атрибуты шаблона new-device-login. Нулевое поле optional — «не задан».
type NewDeviceLoginAttrs struct {
	To         string
	OccurredAt time.Time
	UserId     string
}

var newDeviceLoginDesc = feed.TemplateDesc{
	Name:      "new-device-login",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "user_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendNewDeviceLogin ставит письмо шаблона new-device-login в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendNewDeviceLogin(ctx context.Context, tx pgx.Tx, a NewDeviceLoginAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 2)}
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["user_id"] = a.UserId
	return feed.PutID(ctx, tx, newDeviceLoginDesc, a.To, values)
}
