// Code generated by notifygen. DO NOT EDIT.
// Шаблон user-blocked, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона user-blocked (экспорт для стражей вызывающего, УК70).
const (
	UserBlockedRecipientPerDay = 10
)

// UserBlockedAttrs — атрибуты шаблона user-blocked. Нулевое поле optional — «не задан».
type UserBlockedAttrs struct {
	To         string
	OccurredAt time.Time
	UserId     string
}

var userBlockedDesc = feed.TemplateDesc{
	Name:      "user-blocked",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "user_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendUserBlocked ставит письмо шаблона user-blocked в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendUserBlocked(ctx context.Context, tx pgx.Tx, a UserBlockedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 2)}
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["user_id"] = a.UserId
	return feed.PutID(ctx, tx, userBlockedDesc, a.To, values)
}
