// Code generated by notifygen. DO NOT EDIT.
// Шаблон account-deleted, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона account-deleted (экспорт для стражей вызывающего, УК70).
const (
	AccountDeletedRecipientPerDay = 10
)

// AccountDeletedAttrs — атрибуты шаблона account-deleted. Нулевое поле optional — «не задан».
type AccountDeletedAttrs struct {
	To         string
	AccountId  string
	OccurredAt time.Time
}

var accountDeletedDesc = feed.TemplateDesc{
	Name:      "account-deleted",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "account_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendAccountDeleted ставит письмо шаблона account-deleted в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendAccountDeleted(ctx context.Context, tx pgx.Tx, a AccountDeletedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 2)}
	values.Attrs["account_id"] = a.AccountId
	values.Attrs["occurred_at"] = a.OccurredAt
	return feed.PutID(ctx, tx, accountDeletedDesc, a.To, values)
}
