// Code generated by notifygen. DO NOT EDIT.
// Шаблон recovery-completed, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона recovery-completed (экспорт для стражей вызывающего, УК70).
const (
	RecoveryCompletedRecipientPerDay = 10
)

// RecoveryCompletedAttrs — атрибуты шаблона recovery-completed. Нулевое поле optional — «не задан».
type RecoveryCompletedAttrs struct {
	To         string
	OccurredAt time.Time
	UserId     string
}

var recoveryCompletedDesc = feed.TemplateDesc{
	Name:      "recovery-completed",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       259200 * time.Second,
	Recipient: feed.RecipientSubject,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 10},
	},
	Attrs: []feed.AttrDesc{
		{Name: "occurred_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "user_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendRecoveryCompleted ставит письмо шаблона recovery-completed в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendRecoveryCompleted(ctx context.Context, tx pgx.Tx, a RecoveryCompletedAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 2)}
	values.Attrs["occurred_at"] = a.OccurredAt
	values.Attrs["user_id"] = a.UserId
	return feed.PutID(ctx, tx, recoveryCompletedDesc, a.To, values)
}
