// Code generated by notifygen. DO NOT EDIT.
// Шаблон invite, ревизия 1.

package feedgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
)

// Границы лимитов шаблона invite (экспорт для стражей вызывающего, УК70).
const (
	InviteRecipientPerDay = 50
)

// InviteAttrs — атрибуты шаблона invite. Нулевое поле optional — «не задан».
type InviteAttrs struct {
	To             string
	AccountId      string
	ExpiresAt      time.Time
	InviterAddress string
	Token          string
}

var inviteDesc = feed.TemplateDesc{
	Name:      "invite",
	Class:     feed.ClassSecurity,
	SchemaRev: 1,
	TTL:       86400 * time.Second,
	Recipient: feed.RecipientAddress,
	Limits: []feed.Limit{
		{Scope: feed.ScopeRecipient, WindowSeconds: 86400, Max: 50},
	},
	Attrs: []feed.AttrDesc{
		{Name: "account_id", Kind: form.KindText, Presence: feed.PresenceRequired, Subject: false},
		{Name: "expires_at", Kind: form.KindTimestamp, Presence: feed.PresenceRequired, Subject: false},
		{Name: "inviter_address", Kind: form.KindText, Presence: feed.PresenceOptional, Subject: false},
		{Name: "token", Kind: form.KindToken, Presence: feed.PresenceRequired, Subject: false},
	},
}

// SendInvite ставит письмо шаблона invite в транзакции tx (feed.PutID) и отвечает
// id записанной строки ленты; флаг выключен у notice — строки и id нет.
func SendInvite(ctx context.Context, tx pgx.Tx, a InviteAttrs) (feed.Queued, error) {
	values := feed.Values{Attrs: make(map[string]any, 4)}
	values.Attrs["account_id"] = a.AccountId
	values.Attrs["expires_at"] = a.ExpiresAt
	if _, present, err := form.Presence(form.KindText, a.InviterAddress); err != nil || present == form.Given {
		values.Attrs["inviter_address"] = a.InviterAddress
	}
	values.Attrs["token"] = a.Token
	return feed.PutID(ctx, tx, inviteDesc, a.To, values)
}
