-- Code generated by notifygen init; DO NOT EDIT.
-- notifygen feed schema: service=kaname.kaname version=1

-- +goose Up
CREATE TABLE "kaname"."kaname_notification_outbox" (
  id                text        PRIMARY KEY,
  template          text        NOT NULL,
  schema_rev        integer     NOT NULL CHECK (schema_rev >= 1),
  class             text        NOT NULL CHECK (class IN ('security', 'notice')),
  recipient_address text        NOT NULL,
  attrs             jsonb       NOT NULL,
  secret_attrs      bytea,
  state             text        NOT NULL CHECK (state IN ('pending', 'sent', 'recipient_rejected', 'denied', 'invalid', 'dropped', 'expired')),
  outcome_reason    text,
  outcome_at        timestamptz,
  recorded_kind     text,
  recorded_reason   text,
  outcome_token     uuid,
  lease_token       uuid,
  lease_until       timestamptz,
  first_claimed_at  timestamptz,
  last_defer_reason text,
  not_before        timestamptz CHECK (not_before IS NULL OR isfinite(not_before)),
  enqueued_at       timestamptz NOT NULL DEFAULT now(),
  expires_at        timestamptz NOT NULL,
  CONSTRAINT closed_carries_no_secret CHECK (state = 'pending' OR secret_attrs IS NULL),
  CONSTRAINT outcome_matches_state CHECK ((state <> 'pending') = (outcome_at IS NOT NULL)),
  CONSTRAINT outcome_pair CHECK (
    (state = 'denied' AND outcome_reason IN ('revoked'))
    OR (state = 'dropped' AND outcome_reason IN ('recipient_net'))
    OR (state = 'expired' AND outcome_reason IN ('platform_unavailable', 'grant_skew', 'template_skew', 'recipient_net', 'unclaimed', 'no_ack'))
    OR (state = 'invalid' AND outcome_reason IN ('attrs_invalid', 'class_mismatch', 'recipient_invalid', 'class_not_allowed', 'recipient_form_not_allowed', 'sealed_mismatch', 'key_unavailable'))
    OR (state = 'pending' AND outcome_reason IS NULL)
    OR (state = 'recipient_rejected' AND outcome_reason IS NULL)
    OR (state = 'sent' AND outcome_reason IS NULL))
);
CREATE INDEX "kaname_notification_outbox_pending_idx" ON "kaname"."kaname_notification_outbox" (class, enqueued_at, id) WHERE state = 'pending';
CREATE INDEX "kaname_notification_outbox_closed_idx" ON "kaname"."kaname_notification_outbox" (outcome_at) WHERE state <> 'pending';
CREATE TABLE "kaname"."kaname_notification_window" (
  template       text        NOT NULL,
  scope          text        NOT NULL,
  window_seconds integer     NOT NULL CHECK (window_seconds > 0),
  key            text        NOT NULL,
  window_start   timestamptz NOT NULL,
  count          integer     NOT NULL CHECK (count >= 0),
  PRIMARY KEY (template, scope, window_seconds, key, window_start)
);
CREATE TABLE "kaname"."kaname_notification_contrib" (
  notification_id text        NOT NULL REFERENCES "kaname"."kaname_notification_outbox" (id) ON DELETE CASCADE,
  template        text        NOT NULL,
  scope           text        NOT NULL,
  window_seconds  integer     NOT NULL CHECK (window_seconds > 0),
  key             text        NOT NULL,
  window_start    timestamptz NOT NULL,
  PRIMARY KEY (notification_id, scope, window_seconds)
);

-- +goose Down
DROP TABLE "kaname"."kaname_notification_contrib";
DROP TABLE "kaname"."kaname_notification_window";
DROP TABLE "kaname"."kaname_notification_outbox";
