// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: AGPL-3.0-or-later

package limit

// mapping.go — domain ↔ proto projection for Limit.

import (
	"time"

	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/timestamppb"

	iamv1 "github.com/PRO-Robotech/kacho/pkg/api/kaname/cloud/iam/v1"

	"github.com/PRO-Robotech/kaname/internal/domain"
)

// scopeToProto / scopeFromProto — the closed three-arm mapping, total in both
// directions. The default arm names the unspecified value rather than inventing
// one: a scope guessed here would decide the blast radius of a ceiling.
func scopeToProto(s domain.LimitScope) iamv1.Limit_Scope {
	switch s {
	case domain.LimitScopeDefault:
		return iamv1.Limit_DEFAULT
	case domain.LimitScopeAccount:
		return iamv1.Limit_ACCOUNT
	case domain.LimitScopeProject:
		return iamv1.Limit_PROJECT
	default:
		return iamv1.Limit_SCOPE_UNSPECIFIED
	}
}

func scopeFromProto(s iamv1.Limit_Scope) domain.LimitScope {
	switch s {
	case iamv1.Limit_DEFAULT:
		return domain.LimitScopeDefault
	case iamv1.Limit_ACCOUNT:
		return domain.LimitScopeAccount
	case iamv1.Limit_PROJECT:
		return domain.LimitScopeProject
	default:
		return ""
	}
}

// toProto — projects the stored entity onto the wire.
//
// `created_at` is truncated to SECONDS. The database keeps microseconds; the
// contract says seconds, and it says so for every resource — so the truncation
// belongs here, on the single projection, rather than at each call site where one
// of them would eventually be forgotten.
func toProto(l domain.Limit) *iamv1.Limit {
	out := &iamv1.Limit{
		Id:       string(l.ID),
		Scope:    scopeToProto(l.Scope),
		ScopeId:  l.ScopeID,
		Kind:     string(l.Kind),
		Value:    l.Value,
		Revision: l.Revision,
	}
	if !l.CreatedAt.IsZero() {
		out.CreatedAt = timestamppb.New(l.CreatedAt.Truncate(time.Second))
	}
	return out
}

// effectiveToProto — projects one resolved ceiling.
func effectiveToProto(e domain.EffectiveLimit) *iamv1.EffectiveLimit {
	return &iamv1.EffectiveLimit{
		Kind:          string(e.Kind),
		Value:         e.Value,
		Carrier:       string(e.Carrier),
		SourceScope:   scopeToProto(e.SourceScope),
		SourceScopeId: e.SourceScopeID,
	}
}

// changeToProto — projects one delta entry. The withdrawal is carried by its own
// field rather than by an absent limit: the puller needs the TRIPLE to know what
// to drop, so the row is described even when it no longer applies.
func changeToProto(l domain.Limit) *iamv1.LimitChange {
	return &iamv1.LimitChange{Limit: toProto(l), Withdrawn: l.Withdrawn()}
}

// operationResponse — the response carried by a terminal Operation.
//
// There is no metadata finaliser here on purpose: the id is generated by iam
// BEFORE the operation row is written, so the metadata recorded at Create already
// names the resource.
func operationResponse(l domain.Limit) (*anypb.Any, error) {
	return anypb.New(toProto(l))
}
