// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: AGPL-3.0-or-later

package interactiveclient

// mapping.go — domain ↔ proto projection for InteractiveClient.

import (
	"time"

	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/timestamppb"

	iamv1 "github.com/PRO-Robotech/kacho/pkg/api/kacho/cloud/iam/v1"

	"github.com/PRO-Robotech/kacho-iam/internal/domain"
)

// statusToProto — the domain status is a closed pair, so the mapping is total
// and the default arm names the unspecified value rather than inventing one.
func statusToProto(s domain.InteractiveClientStatus) iamv1.InteractiveClient_Status {
	switch s {
	case domain.InteractiveClientActive:
		return iamv1.InteractiveClient_ACTIVE
	case domain.InteractiveClientDeleting:
		return iamv1.InteractiveClient_DELETING
	default:
		return iamv1.InteractiveClient_STATUS_UNSPECIFIED
	}
}

// toProto — projects the stored entity onto the wire.
//
// `created_at` is truncated to SECONDS. The database keeps microseconds; the
// contract says seconds, and it says so for every resource and every nested
// record — so the truncation belongs here, on the single projection, rather than
// at each call site where one of them would eventually be forgotten.
func toProto(c domain.InteractiveClient) *iamv1.InteractiveClient {
	out := &iamv1.InteractiveClient{
		Id:                      string(c.ID),
		Name:                    string(c.Name),
		Description:             string(c.Description),
		RedirectUris:            c.RedirectURIs,
		PostLogoutRedirectUris:  c.PostLogoutRedirectURIs,
		ClientId:                c.ClientID,
		Audiences:               c.Audiences,
		GrantTypes:              c.GrantTypes,
		TokenEndpointAuthMethod: c.TokenEndpointAuthMethod,
		Status:                  statusToProto(c.Status),
	}
	if !c.CreatedAt.IsZero() {
		out.CreatedAt = timestamppb.New(c.CreatedAt.Truncate(time.Second))
	}
	if len(c.Labels) > 0 {
		out.Labels = make(map[string]string, len(c.Labels))
		for k, v := range c.Labels {
			out.Labels[string(k)] = string(v)
		}
	}
	return out
}

// operationResponse — the response carried by a terminal Operation.
//
// There is no metadata finaliser here on purpose. The id is generated by iam
// BEFORE the operation row is written, so the metadata recorded at Create
// already names the resource — the case MarkDoneWithMetadata exists for (an id
// the database hands back only after the mutation) does not arise.
func operationResponse(c domain.InteractiveClient) (*anypb.Any, error) {
	return anypb.New(toProto(c))
}
