// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/access_key.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessKey — ключ доступа человека (WebAuthn), как его видит владелец в
// перечне (iam Ф7, PRO-Robotech/kacho#1273; приёмка
// `docs/engineering/acceptance/access-keys-are-ours.md`, Р1, Р10).
//
// Ключ — ЭКЗЕМПЛЯР способа входа, а не способ: у человека их несколько, и
// строка способа вида `webauthn` не заводится (Р1). Наружу ключ адресуется
// ТОЛЬКО своим `id` — идентификатор удостоверения WebAuthn, открытый ключ и
// счётчик подписи в контракт не выходят: это байты нормы, а не адрес (Р10).
//
// Полей аттестации нет by construction (Р4): церемония запрашивает «нет», и
// хранить содержимое аттестации нечем. Признаков резервного копирования и
// проверки пользователя нет тоже: различитель ступени берётся из флагов
// КАЖДОГО утверждения, а не из памяти о регистрации (Ф11 Р3, Р1).
type AccessKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Платформенный идентификатор ключа дефисной формы `ak-<17>`; неизменяем на
	// всю жизнь ключа (ban #15). Им ключ снимается и им назван в событии аудита.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Человек, которому принадлежит ключ.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Имя одной формы дерева (DNS label RFC 1123); пустое при заведении
	// замещается `id`. Неизменяемо: глагола правки у ключа нет.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Свободный текст до 256 знаков — «Мой ноутбук». У перенесённого ключа —
	// метка источника, усечённая до предела.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Момент заведения: церемонией либо переносом.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Момент последнего успешного предъявления; не заполнен до первого.
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_kaname_cloud_iam_v1_access_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_access_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_access_key_proto_rawDescGZIP(), []int{0}
}

func (x *AccessKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccessKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

var File_kaname_cloud_iam_v1_access_key_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_access_key_proto_rawDesc = "" +
	"\n" +
	"$kaname/cloud/iam/v1/access_key.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\tAccessKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAtBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_access_key_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_access_key_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_access_key_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_access_key_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_access_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_access_key_proto_rawDesc), len(file_kaname_cloud_iam_v1_access_key_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_access_key_proto_rawDescData
}

var file_kaname_cloud_iam_v1_access_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kaname_cloud_iam_v1_access_key_proto_goTypes = []any{
	(*AccessKey)(nil),             // 0: kaname.cloud.iam.v1.AccessKey
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_access_key_proto_depIdxs = []int32{
	1, // 0: kaname.cloud.iam.v1.AccessKey.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: kaname.cloud.iam.v1.AccessKey.last_used_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_access_key_proto_init() }
func file_kaname_cloud_iam_v1_access_key_proto_init() {
	if File_kaname_cloud_iam_v1_access_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_access_key_proto_rawDesc), len(file_kaname_cloud_iam_v1_access_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kaname_cloud_iam_v1_access_key_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_access_key_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_access_key_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_access_key_proto = out.File
	file_kaname_cloud_iam_v1_access_key_proto_goTypes = nil
	file_kaname_cloud_iam_v1_access_key_proto_depIdxs = nil
}
