// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/account.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An Account resource. Top-level tenant container in kaname.
//
// Account groups Projects and owns custom Roles/Groups/ServiceAccounts. Each Account
// has a single owner_user_id° (User id), which is OUTPUT-ONLY derived-from-caller
// (redesign-2026 F1): not accepted in the Create body (supplying it →
// INVALID_ARGUMENT) and immutable after Create (not in UpdateAccountRequest.update_mask
// → "ownerUserId is immutable after Account.Create").
//
// Resource id prefix: `acc` (concatenated form, `ids.NewID`).
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the account.
	// The name is unique within the IAM domain. 1-63 characters long.
	// Value must match the regular expression `[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?` —
	// RFC 1123 DNS label: lowercase letters, digits and hyphens, 1..63 characters.
	// Empty on Create means "server, name it": a name derived from the id is
	// substituted. Empty on Update is rejected — a resource has no nameless state.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description of the account. 0-256 characters long.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as `key:value` pairs.
	// No more than 64 per resource.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ID of the User who owns this Account (account-administrator). OUTPUT-ONLY,
	// derived-from-caller (mirror of the owner AccessBinding subject). Not accepted
	// in Create (F1) and immutable after Account.Create — including it in
	// UpdateAccount.update_mask returns InvalidArgument
	// ("ownerUserId is immutable after Account.Create").
	OwnerUserId string `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	// Creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Account) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Account that is being created.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// ID of the default Project ("default") co-created by the one-shot Create saga
	// (redesign-2026 F2). Available before the Operation is done, so the client
	// does not have to List the default project. Append-only tag.
	DefaultProjectId string `protobuf:"bytes,2,opt,name=default_project_id,json=defaultProjectId,proto3" json:"default_project_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccountMetadata) Reset() {
	*x = CreateAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountMetadata) ProtoMessage() {}

func (x *CreateAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountMetadata.ProtoReflect.Descriptor instead.
func (*CreateAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountMetadata) GetDefaultProjectId() string {
	if x != nil {
		return x.DefaultProjectId
	}
	return ""
}

type UpdateAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Account that is being updated.
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountMetadata) Reset() {
	*x = UpdateAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountMetadata) ProtoMessage() {}

func (x *UpdateAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountMetadata.ProtoReflect.Descriptor instead.
func (*UpdateAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Account that is being deleted.
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountMetadata) Reset() {
	*x = DeleteAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountMetadata) ProtoMessage() {}

func (x *DeleteAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountMetadata.ProtoReflect.Descriptor instead.
func (*DeleteAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_kaname_cloud_iam_v1_account_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_account_proto_rawDesc = "" +
	"\n" +
	"!kaname/cloud/iam/v1/account.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\x06labels\x18\x04 \x03(\v2(.kaname.cloud.iam.v1.Account.LabelsEntryR\x06labels\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\a\x10\bR\x0forganization_id\"d\n" +
	"\x15CreateAccountMetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12,\n" +
	"\x12default_project_id\x18\x02 \x01(\tR\x10defaultProjectId\"6\n" +
	"\x15UpdateAccountMetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"6\n" +
	"\x15DeleteAccountMetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountIdBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_account_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_account_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_account_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_account_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_account_proto_rawDesc), len(file_kaname_cloud_iam_v1_account_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_account_proto_rawDescData
}

var file_kaname_cloud_iam_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kaname_cloud_iam_v1_account_proto_goTypes = []any{
	(*Account)(nil),               // 0: kaname.cloud.iam.v1.Account
	(*CreateAccountMetadata)(nil), // 1: kaname.cloud.iam.v1.CreateAccountMetadata
	(*UpdateAccountMetadata)(nil), // 2: kaname.cloud.iam.v1.UpdateAccountMetadata
	(*DeleteAccountMetadata)(nil), // 3: kaname.cloud.iam.v1.DeleteAccountMetadata
	nil,                           // 4: kaname.cloud.iam.v1.Account.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_account_proto_depIdxs = []int32{
	4, // 0: kaname.cloud.iam.v1.Account.labels:type_name -> kaname.cloud.iam.v1.Account.LabelsEntry
	5, // 1: kaname.cloud.iam.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_account_proto_init() }
func file_kaname_cloud_iam_v1_account_proto_init() {
	if File_kaname_cloud_iam_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_account_proto_rawDesc), len(file_kaname_cloud_iam_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kaname_cloud_iam_v1_account_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_account_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_account_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_account_proto = out.File
	file_kaname_cloud_iam_v1_account_proto_goTypes = nil
	file_kaname_cloud_iam_v1_account_proto_depIdxs = nil
}
