// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/cluster_service.proto

// ClusterService — the PUBLIC twin of `InternalClusterService`.
//
// Registered on the service's public listener and its public REST front, under
// the canonical `/iam/v1/cluster…` paths. The internal twin stays on the
// internal listener unchanged; both twins execute the SAME use-case instances,
// so the grant table has exactly one write path.
//
// Request and response messages are the internal twin's own (imported from
// `internal_cluster_service.proto`): there is no second form of the same
// subject. Every RPC carries the internal twin's annotations verbatim — the
// permission key, the relation `system_admin` on the singleton
// `cluster:cluster_root` (`scope_extractor.from_request_field = "*"`), and the
// assurance floor: `1` for the reads, `2` for the mutations. `system_admin` is
// declared `[user, service_account]` and is not satisfiable by a wildcard
// tuple, so none of these RPCs is a directory read.
//
// Mutations return an `Operation` that is persisted before the mutation and
// completed by the same request: the caller receives `done = true`, and
// `GET /operations/{operationId}` answers the same envelope.
//
// The "last active admin cannot be revoked" invariant is held by the database
// (one conditional UPDATE under a transaction-scoped lock); the public path
// does not bypass it.

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/api/v1"
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	operation "github.com/PRO-Robotech/corelib/api/corelib/operation"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kaname_cloud_iam_v1_cluster_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_cluster_service_proto_rawDesc = "" +
	"\n" +
	")kaname/cloud/iam/v1/cluster_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1ecorelib/api/v1/operation.proto\x1a!kaname/cloud/iam/v1/cluster.proto\x1a2kaname/cloud/iam/v1/internal_cluster_service.proto\x1a!corelib/operation/operation.proto\x1a$corelib/authz/v1/authz_options.proto2\xf8\x06\n" +
	"\x0eClusterService\x12\xa3\x01\n" +
	"\x03Get\x12&.kaname.cloud.iam.v1.GetClusterRequest\x1a\x1c.kaname.cloud.iam.v1.Cluster\"V\x8a\xb5\x18\x16iam.cluster_admins.get\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x11\x12\x0f/iam/v1/cluster\x12\xf0\x01\n" +
	"\n" +
	"GrantAdmin\x12-.kaname.cloud.iam.v1.GrantClusterAdminRequest\x1a\x1c.corelib.operation.Operation\"\x94\x01\x8a\xb5\x18\x18iam.cluster_admins.grant\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x012\xb2\xd2*.\n" +
	"\x19GrantClusterAdminMetadata\x12\x11ClusterAdminGrant\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/iam/v1/cluster/admins\x12\xfe\x01\n" +
	"\vRevokeAdmin\x12..kaname.cloud.iam.v1.RevokeClusterAdminRequest\x1a\x1c.corelib.operation.Operation\"\xa0\x01\x8a\xb5\x18\x19iam.cluster_admins.revoke\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x012\xb2\xd2*/\n" +
	"\x1aRevokeClusterAdminMetadata\x12\x11ClusterAdminGrant\x82\xd3\xe4\x93\x02%*#/iam/v1/cluster/admins/{subject_id}\x12\xcb\x01\n" +
	"\n" +
	"ListAdmins\x12-.kaname.cloud.iam.v1.ListClusterAdminsRequest\x1a..kaname.cloud.iam.v1.ListClusterAdminsResponse\"^\x8a\xb5\x18\x17iam.cluster_admins.list\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x18\x12\x16/iam/v1/cluster/adminsBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var file_kaname_cloud_iam_v1_cluster_service_proto_goTypes = []any{
	(*GetClusterRequest)(nil),         // 0: kaname.cloud.iam.v1.GetClusterRequest
	(*GrantClusterAdminRequest)(nil),  // 1: kaname.cloud.iam.v1.GrantClusterAdminRequest
	(*RevokeClusterAdminRequest)(nil), // 2: kaname.cloud.iam.v1.RevokeClusterAdminRequest
	(*ListClusterAdminsRequest)(nil),  // 3: kaname.cloud.iam.v1.ListClusterAdminsRequest
	(*Cluster)(nil),                   // 4: kaname.cloud.iam.v1.Cluster
	(*operation.Operation)(nil),       // 5: corelib.operation.Operation
	(*ListClusterAdminsResponse)(nil), // 6: kaname.cloud.iam.v1.ListClusterAdminsResponse
}
var file_kaname_cloud_iam_v1_cluster_service_proto_depIdxs = []int32{
	0, // 0: kaname.cloud.iam.v1.ClusterService.Get:input_type -> kaname.cloud.iam.v1.GetClusterRequest
	1, // 1: kaname.cloud.iam.v1.ClusterService.GrantAdmin:input_type -> kaname.cloud.iam.v1.GrantClusterAdminRequest
	2, // 2: kaname.cloud.iam.v1.ClusterService.RevokeAdmin:input_type -> kaname.cloud.iam.v1.RevokeClusterAdminRequest
	3, // 3: kaname.cloud.iam.v1.ClusterService.ListAdmins:input_type -> kaname.cloud.iam.v1.ListClusterAdminsRequest
	4, // 4: kaname.cloud.iam.v1.ClusterService.Get:output_type -> kaname.cloud.iam.v1.Cluster
	5, // 5: kaname.cloud.iam.v1.ClusterService.GrantAdmin:output_type -> corelib.operation.Operation
	5, // 6: kaname.cloud.iam.v1.ClusterService.RevokeAdmin:output_type -> corelib.operation.Operation
	6, // 7: kaname.cloud.iam.v1.ClusterService.ListAdmins:output_type -> kaname.cloud.iam.v1.ListClusterAdminsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_cluster_service_proto_init() }
func file_kaname_cloud_iam_v1_cluster_service_proto_init() {
	if File_kaname_cloud_iam_v1_cluster_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_cluster_proto_init()
	file_kaname_cloud_iam_v1_internal_cluster_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_cluster_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_cluster_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_cluster_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_cluster_service_proto_depIdxs,
	}.Build()
	File_kaname_cloud_iam_v1_cluster_service_proto = out.File
	file_kaname_cloud_iam_v1_cluster_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_cluster_service_proto_depIdxs = nil
}
