// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/credential_kind.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialKind — ЧЕМ УДОСТОВЕРЕНИЕ СЕБЯ ПРЕДЪЯВЛЯЕТ.
//
// Словарь закрыт. ВЫДАВАЕМЫХ видов ТРИ — KEYPAIR, SECRET, FEDERATED, — потому
// что форм ответа выдачи три, и по виду читатель узнаёт, какое поле ответа
// заполнено:
//
//	вид        | ключевой материал | секрет | чем предъявляется
//	-----------+-------------------+--------+---------------------------------
//	KEYPAIR    | непуст            | пуст   | подписанное утверждение, ключ наш
//	SECRET     | пуст              | непуст | сама строка секрета
//	FEDERATED  | пуст              | пуст   | утверждение ВНЕШНЕГО издателя по
//	           |                   |        | перечню доверенных субъектов
//
// «Пусты оба» у FEDERATED — его ОПРЕДЕЛЯЮЩЕЕ свойство, а не пробел в ответе.
// Схлопнуть его в KEYPAIR значило бы завести дискриминатор, который не
// дискриминирует.
//
// LEGACY ОПИСЫВАЕТ, НО НЕ ВЫДАЁТСЯ. Среди уже лежащих строк есть форма без
// ключевого материала и без перечня доверенных субъектов — удостоверение
// прежнего потока. Она существует независимо от того, назвали мы её или нет;
// отнести её к KEYPAIR значило бы объявить видом, требований которого она не
// выполняет. Названный в запросе выдачи ЯВНО, этот вид отвергается ВСЕГДА и при
// любом составе прочих полей: его не производит ни один глагол, и запрос,
// которым его пытаются выпустить, исполнимого исхода не имеет ни при каком
// входе. Предикат снятия элемента словаря: строк этого вида в обеих таблицах
// ноль — исключение живёт, пока у него есть предмет.
//
// У ЛИЧНОСТИ ВИДОВ ТРИ, А НЕ ЧЕТЫРЕ: FEDERATED недостижим by construction — в
// её контракте нет поля, которым он задаётся.
type CredentialKind int32

const (
	// Вид не назван вызывающим. В запросе выдачи разрешается сохранённым
	// поведением: пустой перечень доверенных субъектов ⇒ KEYPAIR, непустой ⇒
	// FEDERATED. В ОТВЕТЕ и в строке ресурса не встречается никогда — вид
	// ЗАПИСЫВАЕТСЯ при вставке, а читателем не вычисляется.
	CredentialKind_CREDENTIAL_KIND_UNSPECIFIED CredentialKind = 0
	// Ключевая пара ES256. Вызывающий сам собирает и подписывает
	// `client_assertion` (RFC 7521/7523) и обменивает его. Роль вида —
	// федерация, подпись утверждения, долгоживущее доверие.
	CredentialKind_CREDENTIAL_KIND_KEYPAIR CredentialKind = 1
	// Однострочный непрозрачный секрет, предъявляемый КАК ЕСТЬ — в
	// `Authorization: Bearer` на крае и в поле пароля докер-полосы. Ни библиотеки
	// JOSE, ни сборки утверждения, ни обмена. Оплачено коротким объявленным
	// сроком, отзывом на предъявлении и узнаваемой маркой.
	CredentialKind_CREDENTIAL_KIND_SECRET CredentialKind = 2
	// Удостоверение предъявляет ВНЕШНИЙ издатель по перечню доверенных субъектов.
	// Ни ключевого материала, ни секрета у нас нет.
	CredentialKind_CREDENTIAL_KIND_FEDERATED CredentialKind = 3
	// Строка прежнего потока. Не выдаётся НИ ОДНИМ глаголом; появляется только
	// обратным заполнением по фактическому содержимому.
	CredentialKind_CREDENTIAL_KIND_LEGACY CredentialKind = 4
)

// Enum value maps for CredentialKind.
var (
	CredentialKind_name = map[int32]string{
		0: "CREDENTIAL_KIND_UNSPECIFIED",
		1: "CREDENTIAL_KIND_KEYPAIR",
		2: "CREDENTIAL_KIND_SECRET",
		3: "CREDENTIAL_KIND_FEDERATED",
		4: "CREDENTIAL_KIND_LEGACY",
	}
	CredentialKind_value = map[string]int32{
		"CREDENTIAL_KIND_UNSPECIFIED": 0,
		"CREDENTIAL_KIND_KEYPAIR":     1,
		"CREDENTIAL_KIND_SECRET":      2,
		"CREDENTIAL_KIND_FEDERATED":   3,
		"CREDENTIAL_KIND_LEGACY":      4,
	}
)

func (x CredentialKind) Enum() *CredentialKind {
	p := new(CredentialKind)
	*p = x
	return p
}

func (x CredentialKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kaname_cloud_iam_v1_credential_kind_proto_enumTypes[0].Descriptor()
}

func (CredentialKind) Type() protoreflect.EnumType {
	return &file_kaname_cloud_iam_v1_credential_kind_proto_enumTypes[0]
}

func (x CredentialKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialKind.Descriptor instead.
func (CredentialKind) EnumDescriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_credential_kind_proto_rawDescGZIP(), []int{0}
}

var File_kaname_cloud_iam_v1_credential_kind_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_credential_kind_proto_rawDesc = "" +
	"\n" +
	")kaname/cloud/iam/v1/credential_kind.proto\x12\x13kaname.cloud.iam.v1*\xa5\x01\n" +
	"\x0eCredentialKind\x12\x1f\n" +
	"\x1bCREDENTIAL_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CREDENTIAL_KIND_KEYPAIR\x10\x01\x12\x1a\n" +
	"\x16CREDENTIAL_KIND_SECRET\x10\x02\x12\x1d\n" +
	"\x19CREDENTIAL_KIND_FEDERATED\x10\x03\x12\x1a\n" +
	"\x16CREDENTIAL_KIND_LEGACY\x10\x04BBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_credential_kind_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_credential_kind_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_credential_kind_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_credential_kind_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_credential_kind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_credential_kind_proto_rawDesc), len(file_kaname_cloud_iam_v1_credential_kind_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_credential_kind_proto_rawDescData
}

var file_kaname_cloud_iam_v1_credential_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kaname_cloud_iam_v1_credential_kind_proto_goTypes = []any{
	(CredentialKind)(0), // 0: kaname.cloud.iam.v1.CredentialKind
}
var file_kaname_cloud_iam_v1_credential_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_credential_kind_proto_init() }
func file_kaname_cloud_iam_v1_credential_kind_proto_init() {
	if File_kaname_cloud_iam_v1_credential_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_credential_kind_proto_rawDesc), len(file_kaname_cloud_iam_v1_credential_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kaname_cloud_iam_v1_credential_kind_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_credential_kind_proto_depIdxs,
		EnumInfos:         file_kaname_cloud_iam_v1_credential_kind_proto_enumTypes,
	}.Build()
	File_kaname_cloud_iam_v1_credential_kind_proto = out.File
	file_kaname_cloud_iam_v1_credential_kind_proto_goTypes = nil
	file_kaname_cloud_iam_v1_credential_kind_proto_depIdxs = nil
}
