// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/group_service.proto

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/api/v1"
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group resource to return.
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Account to list groups in.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The maximum number of results per page to return. Default value: 100.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A filter expression. Supports filtering by [Group.name].
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListGroupsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListGroupsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGroupsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Group resources.
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// This token allows you to get the next page of results for list requests.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Account that the Group will belong to.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Name of the group. 1-63 characters long, unique within an Account.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the group.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as `key:value` pairs.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group resource to update.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Field mask. Allowed fields: name, description, labels.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Name of the group.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the group.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Resource labels as `key:value` pairs.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DeleteGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group resource to delete.
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AddGroupMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group to add member to.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Тип member'а: "user" | "service_account".
	MemberType string `protobuf:"bytes,2,opt,name=member_type,json=memberType,proto3" json:"member_type,omitempty"`
	// ID member'а (User id или ServiceAccount id).
	MemberId      string `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupMemberRequest) Reset() {
	*x = AddGroupMemberRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMemberRequest) ProtoMessage() {}

func (x *AddGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*AddGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddGroupMemberRequest) GetMemberType() string {
	if x != nil {
		return x.MemberType
	}
	return ""
}

func (x *AddGroupMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type RemoveGroupMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group to remove member from.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Тип member'а.
	MemberType string `protobuf:"bytes,2,opt,name=member_type,json=memberType,proto3" json:"member_type,omitempty"`
	// ID member'а.
	MemberId      string `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetMemberType() string {
	if x != nil {
		return x.MemberType
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type ListGroupMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group to list members for.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The maximum number of results per page to return. Default value: 100.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListGroupMembersRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupMembersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListGroupMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of members of the specified group.
	Members []*GroupMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// This token allows you to get the next page of results for list requests.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListGroupMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListGroupOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Group resource to list operations for.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The maximum number of results per page that should be returned.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupOperationsRequest) Reset() {
	*x = ListGroupOperationsRequest{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupOperationsRequest) ProtoMessage() {}

func (x *ListGroupOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupOperationsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListGroupOperationsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListGroupOperationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListGroupOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of operations for the specified group.
	Operations []*operation.Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	// This token allows you to get the next page of results for list requests.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupOperationsResponse) Reset() {
	*x = ListGroupOperationsResponse{}
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupOperationsResponse) ProtoMessage() {}

func (x *ListGroupOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_group_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupOperationsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListGroupOperationsResponse) GetOperations() []*operation.Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListGroupOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_kaname_cloud_iam_v1_group_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_group_service_proto_rawDesc = "" +
	"\n" +
	"'kaname/cloud/iam/v1/group_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1ecorelib/api/v1/operation.proto\x1a\x1fkaname/cloud/iam/v1/group.proto\x1a%kacho/cloud/operation/operation.proto\x1a$corelib/authz/v1/authz_options.proto\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x86\x01\n" +
	"\x11ListGroupsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"p\n" +
	"\x12ListGroupsResponse\x122\n" +
	"\x06groups\x18\x01 \x03(\v2\x1a.kaname.cloud.iam.v1.GroupR\x06groups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf1\x01\n" +
	"\x12CreateGroupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12K\n" +
	"\x06labels\x18\x04 \x03(\v23.kaname.cloud.iam.v1.CreateGroupRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x02\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12K\n" +
	"\x06labels\x18\x05 \x03(\v23.kaname.cloud.iam.v1.UpdateGroupRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"p\n" +
	"\x15AddGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vmember_type\x18\x02 \x01(\tR\n" +
	"memberType\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\"s\n" +
	"\x18RemoveGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vmember_type\x18\x02 \x01(\tR\n" +
	"memberType\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\"p\n" +
	"\x17ListGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"~\n" +
	"\x18ListGroupMembersResponse\x12:\n" +
	"\amembers\x18\x01 \x03(\v2 .kaname.cloud.iam.v1.GroupMemberR\amembers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"s\n" +
	"\x1aListGroupOperationsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x87\x01\n" +
	"\x1bListGroupOperationsResponse\x12@\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2 .kacho.cloud.operation.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xcd\x0f\n" +
	"\fGroupService\x12\xa3\x01\n" +
	"\x03Get\x12$.kaname.cloud.iam.v1.GetGroupRequest\x1a\x1a.kaname.cloud.iam.v1.Group\"Z\x8a\xb5\x18\x0eiam.groups.get\x92\xb5\x18\x05v_get\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x1b\x12\x19/iam/v1/groups/{group_id}\x12\x86\x01\n" +
	"\x04List\x12&.kaname.cloud.iam.v1.ListGroupsRequest\x1a'.kaname.cloud.iam.v1.ListGroupsResponse\"-\x8a\xb5\x18\x0fiam.groups.list\xb0\xb5\x18\x01\x82\xd3\xe4\x93\x02\x10\x12\x0e/iam/v1/groups\x12\xcb\x01\n" +
	"\x06Create\x12'.kaname.cloud.iam.v1.CreateGroupRequest\x1a .kacho.cloud.operation.Operation\"v\x8a\xb5\x18\x11iam.groups.create\x92\xb5\x18\x06editor\x9a\xb5\x18\x15\n" +
	"\aaccount\x12\n" +
	"account_id\xa2\xb5\x18\x011\xb2\xd2*\x1c\n" +
	"\x13CreateGroupMetadata\x12\x05Group\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/iam/v1/groups\x12\xd9\x01\n" +
	"\x06Update\x12'.kaname.cloud.iam.v1.UpdateGroupRequest\x1a .kacho.cloud.operation.Operation\"\x83\x01\x8a\xb5\x18\x11iam.groups.update\x92\xb5\x18\bv_update\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x011\xb2\xd2*\x1c\n" +
	"\x13UpdateGroupMetadata\x12\x05Group\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/iam/v1/groups/{group_id}\x12\xe6\x01\n" +
	"\x06Delete\x12'.kaname.cloud.iam.v1.DeleteGroupRequest\x1a .kacho.cloud.operation.Operation\"\x90\x01\x8a\xb5\x18\x11iam.groups.delete\x92\xb5\x18\bv_delete\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x012\xb2\xd2*,\n" +
	"\x13DeleteGroupMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02\x1b*\x19/iam/v1/groups/{group_id}\x12\x86\x02\n" +
	"\tAddMember\x12*.kaname.cloud.iam.v1.AddGroupMemberRequest\x1a .kacho.cloud.operation.Operation\"\xaa\x01\x8a\xb5\x18\x1biam.group_members.addMember\x92\xb5\x18\bv_update\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x012\xb2\xd2*/\n" +
	"\x16AddGroupMemberMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02(:\x01*\"#/iam/v1/groups/{group_id}:addMember\x12\x95\x02\n" +
	"\fRemoveMember\x12-.kaname.cloud.iam.v1.RemoveGroupMemberRequest\x1a .kacho.cloud.operation.Operation\"\xb3\x01\x8a\xb5\x18\x1eiam.group_members.removeMember\x92\xb5\x18\bv_update\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x012\xb2\xd2*2\n" +
	"\x19RemoveGroupMemberMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02+:\x01*\"&/iam/v1/groups/{group_id}:removeMember\x12\xe4\x01\n" +
	"\vListMembers\x12,.kaname.cloud.iam.v1.ListGroupMembersRequest\x1a-.kaname.cloud.iam.v1.ListGroupMembersResponse\"x\x8a\xb5\x18\x1fiam.group_memberses.listMembers\x92\xb5\x18\x06v_list\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02'\x12%/iam/v1/groups/{group_id}:listMembers\x12\xf2\x01\n" +
	"\x0eListOperations\x12/.kaname.cloud.iam.v1.ListGroupOperationsRequest\x1a0.kaname.cloud.iam.v1.ListGroupOperationsResponse\"}\x8a\xb5\x18%iam.group_operationses.listOperations\x92\xb5\x18\x06v_list\x9a\xb5\x18\x15\n" +
	"\tiam_group\x12\bgroup_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02&\x12$/iam/v1/groups/{group_id}/operationsBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_group_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_group_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_group_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_group_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_group_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_group_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_group_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_group_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_group_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kaname_cloud_iam_v1_group_service_proto_goTypes = []any{
	(*GetGroupRequest)(nil),             // 0: kaname.cloud.iam.v1.GetGroupRequest
	(*ListGroupsRequest)(nil),           // 1: kaname.cloud.iam.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),          // 2: kaname.cloud.iam.v1.ListGroupsResponse
	(*CreateGroupRequest)(nil),          // 3: kaname.cloud.iam.v1.CreateGroupRequest
	(*UpdateGroupRequest)(nil),          // 4: kaname.cloud.iam.v1.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),          // 5: kaname.cloud.iam.v1.DeleteGroupRequest
	(*AddGroupMemberRequest)(nil),       // 6: kaname.cloud.iam.v1.AddGroupMemberRequest
	(*RemoveGroupMemberRequest)(nil),    // 7: kaname.cloud.iam.v1.RemoveGroupMemberRequest
	(*ListGroupMembersRequest)(nil),     // 8: kaname.cloud.iam.v1.ListGroupMembersRequest
	(*ListGroupMembersResponse)(nil),    // 9: kaname.cloud.iam.v1.ListGroupMembersResponse
	(*ListGroupOperationsRequest)(nil),  // 10: kaname.cloud.iam.v1.ListGroupOperationsRequest
	(*ListGroupOperationsResponse)(nil), // 11: kaname.cloud.iam.v1.ListGroupOperationsResponse
	nil,                                 // 12: kaname.cloud.iam.v1.CreateGroupRequest.LabelsEntry
	nil,                                 // 13: kaname.cloud.iam.v1.UpdateGroupRequest.LabelsEntry
	(*Group)(nil),                       // 14: kaname.cloud.iam.v1.Group
	(*fieldmaskpb.FieldMask)(nil),       // 15: google.protobuf.FieldMask
	(*GroupMember)(nil),                 // 16: kaname.cloud.iam.v1.GroupMember
	(*operation.Operation)(nil),         // 17: kacho.cloud.operation.Operation
}
var file_kaname_cloud_iam_v1_group_service_proto_depIdxs = []int32{
	14, // 0: kaname.cloud.iam.v1.ListGroupsResponse.groups:type_name -> kaname.cloud.iam.v1.Group
	12, // 1: kaname.cloud.iam.v1.CreateGroupRequest.labels:type_name -> kaname.cloud.iam.v1.CreateGroupRequest.LabelsEntry
	15, // 2: kaname.cloud.iam.v1.UpdateGroupRequest.update_mask:type_name -> google.protobuf.FieldMask
	13, // 3: kaname.cloud.iam.v1.UpdateGroupRequest.labels:type_name -> kaname.cloud.iam.v1.UpdateGroupRequest.LabelsEntry
	16, // 4: kaname.cloud.iam.v1.ListGroupMembersResponse.members:type_name -> kaname.cloud.iam.v1.GroupMember
	17, // 5: kaname.cloud.iam.v1.ListGroupOperationsResponse.operations:type_name -> kacho.cloud.operation.Operation
	0,  // 6: kaname.cloud.iam.v1.GroupService.Get:input_type -> kaname.cloud.iam.v1.GetGroupRequest
	1,  // 7: kaname.cloud.iam.v1.GroupService.List:input_type -> kaname.cloud.iam.v1.ListGroupsRequest
	3,  // 8: kaname.cloud.iam.v1.GroupService.Create:input_type -> kaname.cloud.iam.v1.CreateGroupRequest
	4,  // 9: kaname.cloud.iam.v1.GroupService.Update:input_type -> kaname.cloud.iam.v1.UpdateGroupRequest
	5,  // 10: kaname.cloud.iam.v1.GroupService.Delete:input_type -> kaname.cloud.iam.v1.DeleteGroupRequest
	6,  // 11: kaname.cloud.iam.v1.GroupService.AddMember:input_type -> kaname.cloud.iam.v1.AddGroupMemberRequest
	7,  // 12: kaname.cloud.iam.v1.GroupService.RemoveMember:input_type -> kaname.cloud.iam.v1.RemoveGroupMemberRequest
	8,  // 13: kaname.cloud.iam.v1.GroupService.ListMembers:input_type -> kaname.cloud.iam.v1.ListGroupMembersRequest
	10, // 14: kaname.cloud.iam.v1.GroupService.ListOperations:input_type -> kaname.cloud.iam.v1.ListGroupOperationsRequest
	14, // 15: kaname.cloud.iam.v1.GroupService.Get:output_type -> kaname.cloud.iam.v1.Group
	2,  // 16: kaname.cloud.iam.v1.GroupService.List:output_type -> kaname.cloud.iam.v1.ListGroupsResponse
	17, // 17: kaname.cloud.iam.v1.GroupService.Create:output_type -> kacho.cloud.operation.Operation
	17, // 18: kaname.cloud.iam.v1.GroupService.Update:output_type -> kacho.cloud.operation.Operation
	17, // 19: kaname.cloud.iam.v1.GroupService.Delete:output_type -> kacho.cloud.operation.Operation
	17, // 20: kaname.cloud.iam.v1.GroupService.AddMember:output_type -> kacho.cloud.operation.Operation
	17, // 21: kaname.cloud.iam.v1.GroupService.RemoveMember:output_type -> kacho.cloud.operation.Operation
	9,  // 22: kaname.cloud.iam.v1.GroupService.ListMembers:output_type -> kaname.cloud.iam.v1.ListGroupMembersResponse
	11, // 23: kaname.cloud.iam.v1.GroupService.ListOperations:output_type -> kaname.cloud.iam.v1.ListGroupOperationsResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_group_service_proto_init() }
func file_kaname_cloud_iam_v1_group_service_proto_init() {
	if File_kaname_cloud_iam_v1_group_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_group_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_group_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_group_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_group_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_group_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_group_service_proto = out.File
	file_kaname_cloud_iam_v1_group_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_group_service_proto_depIdxs = nil
}
