// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/human_session_service.proto

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveHumanSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The opaque value of the `kaname_session` cookie as the browser sent it.
	// Nothing is read out of it: the service looks the record up by a digest of
	// this value and never stores the value itself.
	Bearer        string `protobuf:"bytes,1,opt,name=bearer,proto3" json:"bearer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHumanSessionRequest) Reset() {
	*x = ResolveHumanSessionRequest{}
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHumanSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHumanSessionRequest) ProtoMessage() {}

func (x *ResolveHumanSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHumanSessionRequest.ProtoReflect.Descriptor instead.
func (*ResolveHumanSessionRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_human_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveHumanSessionRequest) GetBearer() string {
	if x != nil {
		return x.Bearer
	}
	return ""
}

type ResolveHumanSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false — «no session»: one answer for every reason (see the service comment).
	// `session` is then unset.
	Found         bool          `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Session       *HumanSession `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveHumanSessionResponse) Reset() {
	*x = ResolveHumanSessionResponse{}
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHumanSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHumanSessionResponse) ProtoMessage() {}

func (x *ResolveHumanSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHumanSessionResponse.ProtoReflect.Descriptor instead.
func (*ResolveHumanSessionResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_human_session_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveHumanSessionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveHumanSessionResponse) GetSession() *HumanSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// HumanSession — the composition the edge reads (Р1, Ф3-09). Only fields with a
// reader on the edge are here: the set of presented methods and the moment of
// last presentation are read INSIDE the service and deliberately absent (Ф11 Р7).
type HumanSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Our subject id (F4d Р10) — not an external identity.
	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Moment of authentication. Fixed for the life of the session (Ф11 Р6).
	//
	// RESOLUTION ON THE WIRE — MICROSECONDS, NOT SECONDS. This is a NAMED
	// departure from `api-conventions.md` §Timestamps (Ф3 §4.1 п.19, Р7). The
	// edge compares this value inclusively with `SessionCutoffOfResponse.revoke_before`,
	// and a logout / password change dates the cutoff ONE microsecond below the
	// first authentication of the person. Truncating either side to a second
	// would make «S1 stays valid after a logout from S2 in the same second»
	// false by construction. Both compared values cross the wire untruncated;
	// values that are SHOWN (expires_at) keep the convention.
	AuthenticatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	// Absolute expiry — issue moment plus the configured lifetime. Truncated to a
	// second by the convention: the edge does not compare it (the service judges
	// expiry — Ф3-11), it only shows it.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Assurance level by the Ф11 rule (`internal/assurance`): password → "1".
	AssuranceLevel string `protobuf:"bytes,6,opt,name=assurance_level,json=assuranceLevel,proto3" json:"assurance_level,omitempty"`
	// Whether the CURRENT e-mail value has been verified (Ф2 П1).
	EmailVerified bool `protobuf:"varint,7,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanSession) Reset() {
	*x = HumanSession{}
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSession) ProtoMessage() {}

func (x *HumanSession) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSession.ProtoReflect.Descriptor instead.
func (*HumanSession) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_human_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *HumanSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HumanSession) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *HumanSession) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *HumanSession) GetAuthenticatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthenticatedAt
	}
	return nil
}

func (x *HumanSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *HumanSession) GetAssuranceLevel() string {
	if x != nil {
		return x.AssuranceLevel
	}
	return ""
}

func (x *HumanSession) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

var File_kaname_cloud_iam_v1_human_session_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_human_session_service_proto_rawDesc = "" +
	"\n" +
	"/kaname/cloud/iam/v1/human_session_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$corelib/authz/v1/authz_options.proto\"4\n" +
	"\x1aResolveHumanSessionRequest\x12\x16\n" +
	"\x06bearer\x18\x01 \x01(\tR\x06bearer\"p\n" +
	"\x1bResolveHumanSessionResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12;\n" +
	"\asession\x18\x02 \x01(\v2!.kaname.cloud.iam.v1.HumanSessionR\asession\"\xd2\x02\n" +
	"\fHumanSession\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12E\n" +
	"\x10authenticated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fauthenticatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12'\n" +
	"\x0fassurance_level\x18\x06 \x01(\tR\x0eassuranceLevel\x12%\n" +
	"\x0eemail_verified\x18\a \x01(\bR\remailVerifiedJ\x04\b\b\x10\tR\x18password_change_required2\xaf\x01\n" +
	"\x1bInternalHumanSessionService\x12\x8f\x01\n" +
	"\aResolve\x12/.kaname.cloud.iam.v1.ResolveHumanSessionRequest\x1a0.kaname.cloud.iam.v1.ResolveHumanSessionResponse\"!\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x11INTERNAL_LISTENERBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_human_session_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_human_session_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_human_session_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_human_session_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_human_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_human_session_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_human_session_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_human_session_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kaname_cloud_iam_v1_human_session_service_proto_goTypes = []any{
	(*ResolveHumanSessionRequest)(nil),  // 0: kaname.cloud.iam.v1.ResolveHumanSessionRequest
	(*ResolveHumanSessionResponse)(nil), // 1: kaname.cloud.iam.v1.ResolveHumanSessionResponse
	(*HumanSession)(nil),                // 2: kaname.cloud.iam.v1.HumanSession
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_human_session_service_proto_depIdxs = []int32{
	2, // 0: kaname.cloud.iam.v1.ResolveHumanSessionResponse.session:type_name -> kaname.cloud.iam.v1.HumanSession
	3, // 1: kaname.cloud.iam.v1.HumanSession.authenticated_at:type_name -> google.protobuf.Timestamp
	3, // 2: kaname.cloud.iam.v1.HumanSession.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: kaname.cloud.iam.v1.InternalHumanSessionService.Resolve:input_type -> kaname.cloud.iam.v1.ResolveHumanSessionRequest
	1, // 4: kaname.cloud.iam.v1.InternalHumanSessionService.Resolve:output_type -> kaname.cloud.iam.v1.ResolveHumanSessionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_human_session_service_proto_init() }
func file_kaname_cloud_iam_v1_human_session_service_proto_init() {
	if File_kaname_cloud_iam_v1_human_session_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_human_session_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_human_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_human_session_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_human_session_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_human_session_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_human_session_service_proto = out.File
	file_kaname_cloud_iam_v1_human_session_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_human_session_service_proto_depIdxs = nil
}
