// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kaname/cloud/iam/v1/identity_quota_service.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityQuotaService_List_FullMethodName = "/kaname.cloud.iam.v1.IdentityQuotaService/List"
)

// IdentityQuotaServiceClient is the client API for IdentityQuotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityQuotaService — the ceilings carried by the CALLER THEMSELVES.
//
// # Why this service is declared HERE, in the access service's own contract
//
// It answers about a ceiling this service enforces, in a row of this service's
// own database, and it calls nobody. A tenant-facing surface of a product being
// carved out into its own must be declared in that product's contract —
// otherwise the module it was declared inside takes the surface with it when it
// leaves, though the subject of the surface stays (kacho#2362, decision `Д9`).
//
// A PREVIOUS COMMENT HERE SAID THE OPPOSITE, AND ITS PREMISE HAD DIED. It read:
// the shared answer shape imports `kaname.cloud.iam.v1`, so declaring the
// service inside `iam.v1` would close a package cycle. That was true when it was
// written and is no longer: the shared shape has NO imports at all today — it
// states the scope arm itself, precisely so the platform keeps building once
// this contract is removed. The dependency runs one way and only one way, and
// this file adds an edge in the direction that already exists.
//
// This is NOT the "single summary endpoint" the shared shape's doc rules out.
// That one is refused because it would need `iam -> owner` calls to learn what is
// spent elsewhere, closing a cycle in the service graph. This service answers
// about ONE kind, counted in this service's own database, and calls nobody.
//
// # Why the subject is a human and not a project
//
// The account is the root of tenancy, so a ceiling over accounts is carried by
// the identity that creates them — the only thing that exists before an account
// and outlives it. There is no project to name here, and naming one would be a
// question about the wrong subject.
//
// # Why the tenant must be able to read this
//
// Account creation is self-service. Until this service existed the ceiling over
// it was invisible: a human who had reached it saw a refusal on the one action
// the platform invites them to perform first, with no way to learn their ceiling,
// their consumption, or that a ceiling exists at all — indistinguishable, from
// their side, from a broken platform.
//
// READ ONLY. A tenant who can raise their own ceiling does not have one.
type IdentityQuotaServiceClient interface {
	// List the quotas carried by the calling identity.
	//
	// NO REQUEST FIELDS, AND THAT IS THE POINT. The subject is the authenticated
	// caller and nobody else: there is no id to supply, so there is no id to
	// substitute. One identity cannot ask about another's consumption because the
	// question is not expressible — a stronger guarantee than a check that would
	// have to be right every time.
	//
	// NO PAGINATION, DELIBERATELY. One kind is carried by the identity today, and
	// the catalogue that could add more is closed and bounded by a migration.
	//
	// THE HTTP PATH IS UNCHANGED BY THE MOVE, and that is the point of the move
	// being a move: the tenant's URL, the response shape, and every field name and
	// number are what they have always been. What changed is which contract
	// declares them.
	List(ctx context.Context, in *ListIdentityQuotasRequest, opts ...grpc.CallOption) (*ListIdentityQuotasResponse, error)
}

type identityQuotaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityQuotaServiceClient(cc grpc.ClientConnInterface) IdentityQuotaServiceClient {
	return &identityQuotaServiceClient{cc}
}

func (c *identityQuotaServiceClient) List(ctx context.Context, in *ListIdentityQuotasRequest, opts ...grpc.CallOption) (*ListIdentityQuotasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentityQuotasResponse)
	err := c.cc.Invoke(ctx, IdentityQuotaService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityQuotaServiceServer is the server API for IdentityQuotaService service.
// All implementations must embed UnimplementedIdentityQuotaServiceServer
// for forward compatibility.
//
// IdentityQuotaService — the ceilings carried by the CALLER THEMSELVES.
//
// # Why this service is declared HERE, in the access service's own contract
//
// It answers about a ceiling this service enforces, in a row of this service's
// own database, and it calls nobody. A tenant-facing surface of a product being
// carved out into its own must be declared in that product's contract —
// otherwise the module it was declared inside takes the surface with it when it
// leaves, though the subject of the surface stays (kacho#2362, decision `Д9`).
//
// A PREVIOUS COMMENT HERE SAID THE OPPOSITE, AND ITS PREMISE HAD DIED. It read:
// the shared answer shape imports `kaname.cloud.iam.v1`, so declaring the
// service inside `iam.v1` would close a package cycle. That was true when it was
// written and is no longer: the shared shape has NO imports at all today — it
// states the scope arm itself, precisely so the platform keeps building once
// this contract is removed. The dependency runs one way and only one way, and
// this file adds an edge in the direction that already exists.
//
// This is NOT the "single summary endpoint" the shared shape's doc rules out.
// That one is refused because it would need `iam -> owner` calls to learn what is
// spent elsewhere, closing a cycle in the service graph. This service answers
// about ONE kind, counted in this service's own database, and calls nobody.
//
// # Why the subject is a human and not a project
//
// The account is the root of tenancy, so a ceiling over accounts is carried by
// the identity that creates them — the only thing that exists before an account
// and outlives it. There is no project to name here, and naming one would be a
// question about the wrong subject.
//
// # Why the tenant must be able to read this
//
// Account creation is self-service. Until this service existed the ceiling over
// it was invisible: a human who had reached it saw a refusal on the one action
// the platform invites them to perform first, with no way to learn their ceiling,
// their consumption, or that a ceiling exists at all — indistinguishable, from
// their side, from a broken platform.
//
// READ ONLY. A tenant who can raise their own ceiling does not have one.
type IdentityQuotaServiceServer interface {
	// List the quotas carried by the calling identity.
	//
	// NO REQUEST FIELDS, AND THAT IS THE POINT. The subject is the authenticated
	// caller and nobody else: there is no id to supply, so there is no id to
	// substitute. One identity cannot ask about another's consumption because the
	// question is not expressible — a stronger guarantee than a check that would
	// have to be right every time.
	//
	// NO PAGINATION, DELIBERATELY. One kind is carried by the identity today, and
	// the catalogue that could add more is closed and bounded by a migration.
	//
	// THE HTTP PATH IS UNCHANGED BY THE MOVE, and that is the point of the move
	// being a move: the tenant's URL, the response shape, and every field name and
	// number are what they have always been. What changed is which contract
	// declares them.
	List(context.Context, *ListIdentityQuotasRequest) (*ListIdentityQuotasResponse, error)
	mustEmbedUnimplementedIdentityQuotaServiceServer()
}

// UnimplementedIdentityQuotaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityQuotaServiceServer struct{}

func (UnimplementedIdentityQuotaServiceServer) List(context.Context, *ListIdentityQuotasRequest) (*ListIdentityQuotasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedIdentityQuotaServiceServer) mustEmbedUnimplementedIdentityQuotaServiceServer() {}
func (UnimplementedIdentityQuotaServiceServer) testEmbeddedByValue()                              {}

// UnsafeIdentityQuotaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityQuotaServiceServer will
// result in compilation errors.
type UnsafeIdentityQuotaServiceServer interface {
	mustEmbedUnimplementedIdentityQuotaServiceServer()
}

func RegisterIdentityQuotaServiceServer(s grpc.ServiceRegistrar, srv IdentityQuotaServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityQuotaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityQuotaService_ServiceDesc, srv)
}

func _IdentityQuotaService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentityQuotasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityQuotaServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityQuotaService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityQuotaServiceServer).List(ctx, req.(*ListIdentityQuotasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityQuotaService_ServiceDesc is the grpc.ServiceDesc for IdentityQuotaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityQuotaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaname.cloud.iam.v1.IdentityQuotaService",
	HandlerType: (*IdentityQuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _IdentityQuotaService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaname/cloud/iam/v1/identity_quota_service.proto",
}
