// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kaname/cloud/iam/v1/internal_interactive_client_service.proto

// InternalInteractiveClientService — Internal-only.
// Registered exclusively on the api-gateway internal mux (cluster-internal
// listener) under `/iam/v1/internal/interactiveClients`; never on the external
// TLS endpoint (ban #6). The dispatcher — not the absence of a route — is what
// keeps it off the outside: `isInternalRoute` is keyed on the (method, path)
// pair and answers 404 for external origin, hiding existence.
//
// WHAT IT MANAGES. The OAuth2 client through which a human completes an
// interactive sign-in ceremony. Registering one is a credential-lifecycle act,
// so it is admin-only and lives behind mTLS + a per-RPC authz Check like every
// other Internal* RPC (security.md: authN+authZ on BOTH listeners).
//
// AUTHENTICATION FLOOR (decision Р4 — no floor is ever lowered).
// `Create` / `Update` / `Delete` declare `required_acr_min = "2"`: they change
// the security posture — a redirect target is where an authorization code is
// delivered, so editing the list redirects credentials. `Get` / `List` declare
// `"1"`: reading a client is not issuing a credential. Every RPC declares its
// floor EXPLICITLY, because the generator's default is "2"
// (protoc-gen-kacho-permissions `DefaultRequiredAcrMin`) and an unstated floor
// would arrive as sensitive by accident rather than by decision.
//
// ASYNC CONTRACT. Mutations return `Operation` (ban #9); `done` means the
// subject of the mutation is durable and is never gated on the visibility of
// anything downstream.

package iamv1

import (
	context "context"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalInteractiveClientService_Get_FullMethodName    = "/kaname.cloud.iam.v1.InternalInteractiveClientService/Get"
	InternalInteractiveClientService_List_FullMethodName   = "/kaname.cloud.iam.v1.InternalInteractiveClientService/List"
	InternalInteractiveClientService_Create_FullMethodName = "/kaname.cloud.iam.v1.InternalInteractiveClientService/Create"
	InternalInteractiveClientService_Update_FullMethodName = "/kaname.cloud.iam.v1.InternalInteractiveClientService/Update"
	InternalInteractiveClientService_Delete_FullMethodName = "/kaname.cloud.iam.v1.InternalInteractiveClientService/Delete"
)

// InternalInteractiveClientServiceClient is the client API for InternalInteractiveClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalInteractiveClientService — admin-tooling for the interactive-login
// client. See the file-level comment for the gate and the async contract.
type InternalInteractiveClientServiceClient interface {
	// Returns the requested InteractiveClient. Sync read; no Operation envelope.
	//
	// A malformed id is rejected synchronously as `INVALID_ARGUMENT` by the
	// first statement of the RPC; a well-formed id with no row is `NOT_FOUND`
	// (direct-read lane — this is iam's own resource).
	//
	// REST exposed ONLY on the cluster-internal listener.
	Get(ctx context.Context, in *GetInteractiveClientRequest, opts ...grpc.CallOption) (*InteractiveClient, error)
	// Lists InteractiveClients. Sync read, cursor-paginated on `(created_at, id)`.
	//
	// REST exposed ONLY on the cluster-internal listener.
	List(ctx context.Context, in *ListInteractiveClientsRequest, opts ...grpc.CallOption) (*ListInteractiveClientsResponse, error)
	// Registers a new interactive-login client at the identity provider and
	// records it. The provider call happens on the request path and is
	// fail-closed: if the provider is unreachable the mutation ends
	// `UNAVAILABLE` and leaves NO row behind — the name does not stay taken.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Create(ctx context.Context, in *CreateInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Updates the mutable fields of an InteractiveClient
	// (`name`, `description`, `labels`, `redirect_uris`,
	// `post_logout_redirect_uris`). Output-only fields are immutable and are
	// rejected by name when named in the mask.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Update(ctx context.Context, in *UpdateInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Removes the client at the identity provider and its row. Idempotent —
	// deleting an already-absent client does not differ in code from the first
	// delete.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Delete(ctx context.Context, in *DeleteInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error)
}

type internalInteractiveClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalInteractiveClientServiceClient(cc grpc.ClientConnInterface) InternalInteractiveClientServiceClient {
	return &internalInteractiveClientServiceClient{cc}
}

func (c *internalInteractiveClientServiceClient) Get(ctx context.Context, in *GetInteractiveClientRequest, opts ...grpc.CallOption) (*InteractiveClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractiveClient)
	err := c.cc.Invoke(ctx, InternalInteractiveClientService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalInteractiveClientServiceClient) List(ctx context.Context, in *ListInteractiveClientsRequest, opts ...grpc.CallOption) (*ListInteractiveClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInteractiveClientsResponse)
	err := c.cc.Invoke(ctx, InternalInteractiveClientService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalInteractiveClientServiceClient) Create(ctx context.Context, in *CreateInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalInteractiveClientService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalInteractiveClientServiceClient) Update(ctx context.Context, in *UpdateInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalInteractiveClientService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalInteractiveClientServiceClient) Delete(ctx context.Context, in *DeleteInteractiveClientRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalInteractiveClientService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalInteractiveClientServiceServer is the server API for InternalInteractiveClientService service.
// All implementations must embed UnimplementedInternalInteractiveClientServiceServer
// for forward compatibility.
//
// InternalInteractiveClientService — admin-tooling for the interactive-login
// client. See the file-level comment for the gate and the async contract.
type InternalInteractiveClientServiceServer interface {
	// Returns the requested InteractiveClient. Sync read; no Operation envelope.
	//
	// A malformed id is rejected synchronously as `INVALID_ARGUMENT` by the
	// first statement of the RPC; a well-formed id with no row is `NOT_FOUND`
	// (direct-read lane — this is iam's own resource).
	//
	// REST exposed ONLY on the cluster-internal listener.
	Get(context.Context, *GetInteractiveClientRequest) (*InteractiveClient, error)
	// Lists InteractiveClients. Sync read, cursor-paginated on `(created_at, id)`.
	//
	// REST exposed ONLY on the cluster-internal listener.
	List(context.Context, *ListInteractiveClientsRequest) (*ListInteractiveClientsResponse, error)
	// Registers a new interactive-login client at the identity provider and
	// records it. The provider call happens on the request path and is
	// fail-closed: if the provider is unreachable the mutation ends
	// `UNAVAILABLE` and leaves NO row behind — the name does not stay taken.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Create(context.Context, *CreateInteractiveClientRequest) (*operation.Operation, error)
	// Updates the mutable fields of an InteractiveClient
	// (`name`, `description`, `labels`, `redirect_uris`,
	// `post_logout_redirect_uris`). Output-only fields are immutable and are
	// rejected by name when named in the mask.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Update(context.Context, *UpdateInteractiveClientRequest) (*operation.Operation, error)
	// Removes the client at the identity provider and its row. Idempotent —
	// deleting an already-absent client does not differ in code from the first
	// delete.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Delete(context.Context, *DeleteInteractiveClientRequest) (*operation.Operation, error)
	mustEmbedUnimplementedInternalInteractiveClientServiceServer()
}

// UnimplementedInternalInteractiveClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalInteractiveClientServiceServer struct{}

func (UnimplementedInternalInteractiveClientServiceServer) Get(context.Context, *GetInteractiveClientRequest) (*InteractiveClient, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInternalInteractiveClientServiceServer) List(context.Context, *ListInteractiveClientsRequest) (*ListInteractiveClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInternalInteractiveClientServiceServer) Create(context.Context, *CreateInteractiveClientRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInternalInteractiveClientServiceServer) Update(context.Context, *UpdateInteractiveClientRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedInternalInteractiveClientServiceServer) Delete(context.Context, *DeleteInteractiveClientRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedInternalInteractiveClientServiceServer) mustEmbedUnimplementedInternalInteractiveClientServiceServer() {
}
func (UnimplementedInternalInteractiveClientServiceServer) testEmbeddedByValue() {}

// UnsafeInternalInteractiveClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalInteractiveClientServiceServer will
// result in compilation errors.
type UnsafeInternalInteractiveClientServiceServer interface {
	mustEmbedUnimplementedInternalInteractiveClientServiceServer()
}

func RegisterInternalInteractiveClientServiceServer(s grpc.ServiceRegistrar, srv InternalInteractiveClientServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalInteractiveClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalInteractiveClientService_ServiceDesc, srv)
}

func _InternalInteractiveClientService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractiveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalInteractiveClientServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalInteractiveClientService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalInteractiveClientServiceServer).Get(ctx, req.(*GetInteractiveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalInteractiveClientService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInteractiveClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalInteractiveClientServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalInteractiveClientService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalInteractiveClientServiceServer).List(ctx, req.(*ListInteractiveClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalInteractiveClientService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInteractiveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalInteractiveClientServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalInteractiveClientService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalInteractiveClientServiceServer).Create(ctx, req.(*CreateInteractiveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalInteractiveClientService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInteractiveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalInteractiveClientServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalInteractiveClientService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalInteractiveClientServiceServer).Update(ctx, req.(*UpdateInteractiveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalInteractiveClientService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInteractiveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalInteractiveClientServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalInteractiveClientService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalInteractiveClientServiceServer).Delete(ctx, req.(*DeleteInteractiveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalInteractiveClientService_ServiceDesc is the grpc.ServiceDesc for InternalInteractiveClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalInteractiveClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaname.cloud.iam.v1.InternalInteractiveClientService",
	HandlerType: (*InternalInteractiveClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _InternalInteractiveClientService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _InternalInteractiveClientService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _InternalInteractiveClientService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _InternalInteractiveClientService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _InternalInteractiveClientService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaname/cloud/iam/v1/internal_interactive_client_service.proto",
}
