// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kaname/cloud/iam/v1/internal_notification_recipient_service.proto

// InternalNotificationRecipientService — справочник адресов получателей писем
// (приёмка NTF-3 Р7, Р28). Internal-only (cluster-internal listener, mTLS).
//
// НИ ОДНОЙ REST-привязки — намеренно и как инвариант (NTF3-30): служба не
// маршрутизируется ни на внешний край, ни на REST внутреннего края. Достижима
// только прямым gRPC по mTLS на внутренний слушатель kaname; имя
// `Internal…Service` не публикуется на внешнем слушателе (ban #6).
//
// Вызывающий один — служебный принципал `service:notify` звена Р2: методы
// внесены в закрытый перечень методов звена в корне kaname. Право — вопрос
// `reader` на `notification_recipient_directory:root` той же дверью, что
// отвечает `InternalIAMService/Check`; кортеж заводит только строка манифеста
// `notify` `recipientDirectory: {readers: [notify]}`. Тип справочника — в
// перечне типов без надзора администратора облака: адресов мимо модели не
// читает никто. Отказ права — `PERMISSION_DENIED` `permission denied`,
// `ErrorInfo{reason: AUTHZ_DENIED}`; право решается до проверки входа.
//
// Исход по субъекту — в теле ответа, а не кодом: справочник не производит
// `NOT_FOUND`, `ALREADY_EXISTS`, `FAILED_PRECONDITION`. Сбой чтения хранилища
// kaname — `UNAVAILABLE` фиксированным текстом `notification recipient
// directory temporarily unavailable`.

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalNotificationRecipientService_Resolve_FullMethodName             = "/kaname.cloud.iam.v1.InternalNotificationRecipientService/Resolve"
	InternalNotificationRecipientService_ListProjectAudience_FullMethodName = "/kaname.cloud.iam.v1.InternalNotificationRecipientService/ListProjectAudience"
)

// InternalNotificationRecipientServiceClient is the client API for InternalNotificationRecipientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalNotificationRecipientService — справочник адресов. См. шапку файла.
type InternalNotificationRecipientServiceClient interface {
	// Resolve — исход и адрес одного получателя письма. Чтение, а не мутация:
	// `Operation` не возвращается.
	//
	// Проверка входа — синхронно, в порядке: (1) обязательность (`<field>:
	// required`); (2) `subject` при `account_owner` — `subject: must be empty
	// for audience account_owner`; (3) тип ссылки, отношение, число ссылок и
	// смесь типов. Вопрос к модели о праве получателя задаётся только после
	// проверки входа целиком.
	Resolve(ctx context.Context, in *ResolveRecipientRequest, opts ...grpc.CallOption) (*ResolveRecipientResponse, error)
	// ListProjectAudience — субъекты `user:<id>` с действующей (не отозванной,
	// не истёкшей) привязкой с субъектом-пользователем на `project:<id>`.
	// Группы не раскрываются, привязки аккаунта не входят, адресов в ответе нет.
	//
	// Порядок — по id пользователя по возрастанию; курсор — позиция последнего
	// выданного id. Отступление от курсора `(created_at, id)` названо: элемент
	// выдачи — пользователь, выведенный из одной или нескольких привязок, своего
	// `created_at` у него нет, и пользователь с двумя привязками под курсором
	// привязки выдавался бы дважды.
	ListProjectAudience(ctx context.Context, in *ListProjectAudienceRequest, opts ...grpc.CallOption) (*ListProjectAudienceResponse, error)
}

type internalNotificationRecipientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalNotificationRecipientServiceClient(cc grpc.ClientConnInterface) InternalNotificationRecipientServiceClient {
	return &internalNotificationRecipientServiceClient{cc}
}

func (c *internalNotificationRecipientServiceClient) Resolve(ctx context.Context, in *ResolveRecipientRequest, opts ...grpc.CallOption) (*ResolveRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveRecipientResponse)
	err := c.cc.Invoke(ctx, InternalNotificationRecipientService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalNotificationRecipientServiceClient) ListProjectAudience(ctx context.Context, in *ListProjectAudienceRequest, opts ...grpc.CallOption) (*ListProjectAudienceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectAudienceResponse)
	err := c.cc.Invoke(ctx, InternalNotificationRecipientService_ListProjectAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalNotificationRecipientServiceServer is the server API for InternalNotificationRecipientService service.
// All implementations must embed UnimplementedInternalNotificationRecipientServiceServer
// for forward compatibility.
//
// InternalNotificationRecipientService — справочник адресов. См. шапку файла.
type InternalNotificationRecipientServiceServer interface {
	// Resolve — исход и адрес одного получателя письма. Чтение, а не мутация:
	// `Operation` не возвращается.
	//
	// Проверка входа — синхронно, в порядке: (1) обязательность (`<field>:
	// required`); (2) `subject` при `account_owner` — `subject: must be empty
	// for audience account_owner`; (3) тип ссылки, отношение, число ссылок и
	// смесь типов. Вопрос к модели о праве получателя задаётся только после
	// проверки входа целиком.
	Resolve(context.Context, *ResolveRecipientRequest) (*ResolveRecipientResponse, error)
	// ListProjectAudience — субъекты `user:<id>` с действующей (не отозванной,
	// не истёкшей) привязкой с субъектом-пользователем на `project:<id>`.
	// Группы не раскрываются, привязки аккаунта не входят, адресов в ответе нет.
	//
	// Порядок — по id пользователя по возрастанию; курсор — позиция последнего
	// выданного id. Отступление от курсора `(created_at, id)` названо: элемент
	// выдачи — пользователь, выведенный из одной или нескольких привязок, своего
	// `created_at` у него нет, и пользователь с двумя привязками под курсором
	// привязки выдавался бы дважды.
	ListProjectAudience(context.Context, *ListProjectAudienceRequest) (*ListProjectAudienceResponse, error)
	mustEmbedUnimplementedInternalNotificationRecipientServiceServer()
}

// UnimplementedInternalNotificationRecipientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalNotificationRecipientServiceServer struct{}

func (UnimplementedInternalNotificationRecipientServiceServer) Resolve(context.Context, *ResolveRecipientRequest) (*ResolveRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedInternalNotificationRecipientServiceServer) ListProjectAudience(context.Context, *ListProjectAudienceRequest) (*ListProjectAudienceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjectAudience not implemented")
}
func (UnimplementedInternalNotificationRecipientServiceServer) mustEmbedUnimplementedInternalNotificationRecipientServiceServer() {
}
func (UnimplementedInternalNotificationRecipientServiceServer) testEmbeddedByValue() {}

// UnsafeInternalNotificationRecipientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalNotificationRecipientServiceServer will
// result in compilation errors.
type UnsafeInternalNotificationRecipientServiceServer interface {
	mustEmbedUnimplementedInternalNotificationRecipientServiceServer()
}

func RegisterInternalNotificationRecipientServiceServer(s grpc.ServiceRegistrar, srv InternalNotificationRecipientServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalNotificationRecipientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalNotificationRecipientService_ServiceDesc, srv)
}

func _InternalNotificationRecipientService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNotificationRecipientServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNotificationRecipientService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNotificationRecipientServiceServer).Resolve(ctx, req.(*ResolveRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalNotificationRecipientService_ListProjectAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNotificationRecipientServiceServer).ListProjectAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNotificationRecipientService_ListProjectAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNotificationRecipientServiceServer).ListProjectAudience(ctx, req.(*ListProjectAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalNotificationRecipientService_ServiceDesc is the grpc.ServiceDesc for InternalNotificationRecipientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalNotificationRecipientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaname.cloud.iam.v1.InternalNotificationRecipientService",
	HandlerType: (*InternalNotificationRecipientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _InternalNotificationRecipientService_Resolve_Handler,
		},
		{
			MethodName: "ListProjectAudience",
			Handler:    _InternalNotificationRecipientService_ListProjectAudience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaname/cloud/iam/v1/internal_notification_recipient_service.proto",
}
