// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/internal_bootstrap_token_service.proto

// InternalBootstrapTokenService — Internal-only (cluster-internal :9091, mTLS).
// Reachable ONLY by a DIRECT mTLS gRPC dial to kaname-internal :9091. It carries NO
// `google.api.http` binding and is NOT registered on the api-gateway REST mux —
// deliberately, and this is a SECURITY invariant, not a style choice: the
// gateway's cluster-internal REST listener is plain HTTP/1.1 (no TLS, no client
// cert) and the authz middleware admits `<exempt>` Internal* RPCs arriving there
// WITHOUT extracting a principal, so a REST route would make this a
// credential-free cluster-admin token mint for anything that can reach the
// `internal-rest` Service port (or hold a port-forward). Never on the external
// TLS endpoint either (the `Internal…Service` name matches `HasInternalSuffix`,
// so the gRPC router 404s it on the public listener — ban #6).
//
// Purpose (#58): a NON-INTERACTIVE entry point to a first real asymmetric Bearer
// for production-mode seed. Production authN (`api-gateway
// authn.mode=production-strict`) verifies the signature against the key-set
// record of the issuer NAMED IN THE TOKEN (the gateway reads both records from
// the iam publisher on :9097) and requires `aud=https://{API_DOMAIN}`.
// Newman/e2e seed mints HS256 dev JWTs → inert against a production stand, and a
// fresh stand has no seeded machine credential at all, so without this service
// the only path to a first token is a human browser ceremony at the identity
// provider — which blocks ALL production e2e.
//
// This service idempotently provisions a SINGLE bootstrap-admin ServiceAccount
// (cluster `system_admin`) and mints a short-lived access-token for it.
//
// WHO SIGNS THAT TOKEN DEPENDS ON THE DEPLOYMENT, and this line used to claim
// otherwise. It said "Hydra remains the issuer / signer; iam only brokers the
// exchange (never re-signs)" — the claim outlived its subject (#1119). Today:
//
//   own minting declared → the PLATFORM signer mints it (internal/tokensigner,
//                          wired through internal/bootstraptokenwire);
//   not declared         → the provider mints it, brokered through the existing
//                          client_credentials exchange, and the bootstrap-admin
//                          gets a mirrored OAuth client (client_credentials +
//                          private_key_jwt) as before.
//
// Only the requested `audience` differs from the registry lane —
// `https://{API_DOMAIN}` vs the registry service.
//
// Principal = a ServiceAccount, NOT a User, because service principals are
// acr-EXEMPT by design (security.md §4.1.2; iam authzguard/fgaproxy): the minted
// token then satisfies the acr>=2-gated seed RPCs
// (`UserTokenService.Issue` / `SAKeyService.Issue`) without any acr injection.
//
// Scope discipline: mints ONLY the bootstrap-admin SA. There is deliberately NO
// subject/principal field in the request — a "mint token for any principal"
// skeleton-key is rejected by construction (acceptance IBT-11 / D-2).
//
// Authorization gate: an EXPLICIT per-RPC allow-list of client-certificate
// SPIFFE SANs, enforced on the :9091 listener by
// `authzguard.CallerPolicy` (`authn.bootstrap-mint.allowed-client-sans`). The
// gate is the caller's VERIFIED CLIENT CERTIFICATE — a named identity — NOT its
// network position: "internal = trusted" / "the listener boundary is the gate"
// are FORBIDDEN premises (security.md §authN-everywhere). An empty allow-list
// denies every caller (fail-closed, no default caller), and an ENABLED mint
// (signing key present) with an empty allow-list REFUSES TO BOOT in production
// (`Config.Validate`, core rule #16).
//
// `permission = "<exempt>"` marks only that there is no per-RPC FGA/ReBAC Check:
// this RPC exists to obtain the FIRST token on a stand where no token — and
// therefore no relation to check — exists yet (chicken-and-egg). `<exempt>` is
// NOT an authentication exemption; the cert allow-list above is the authN+authZ
// gate.

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MintBootstrapTokenRequest — inputs for MintBootstrapToken.
//
// There is DELIBERATELY no subject/principal field: the RPC mints exclusively
// for the bootstrap-admin SA (IBT-11). Any unknown key a client sends is ignored
// by grpc-gateway and cannot influence the principal.
type MintBootstrapTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintBootstrapTokenRequest) Reset() {
	*x = MintBootstrapTokenRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintBootstrapTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintBootstrapTokenRequest) ProtoMessage() {}

func (x *MintBootstrapTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintBootstrapTokenRequest.ProtoReflect.Descriptor instead.
func (*MintBootstrapTokenRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescGZIP(), []int{0}
}

// MintBootstrapTokenResponse — the minted bootstrap Bearer.
type MintBootstrapTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RS256 JWT access-token (Hydra-signed; `alg=RS256`, Hydra `kid`). The
	// gateway accepts it as a valid production-mode Bearer.
	//
	// Помечен носителем секрета: это привилегированный предъявитель. Ответ
	// СИНХРОННЫЙ, в строку операции не попадает вовсе — поэтому перечня
	// подметальщика он не требует (ось 1 гейта сужена типами-ответами операций).
	// Пометка здесь объявляет ВИД поля: любой заведённый завтра путь записи
	// увидит её, не зная про этот глагол.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// OAuth2 token type — always `"Bearer"`.
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// Seconds until expiry (`expires_at - issued_at`) — the lifetime the issuer
	// gave the token. Never understated: the bearer is accepted for exactly this
	// long, so the holder can rely on it to revoke or rotate in time.
	ExpiresIn int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Absolute expiry (truncated to seconds).
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// The bootstrap ServiceAccount id (`sva…`) this token authenticates as —
	// equals the token's `kaname_principal_id` claim.
	PrincipalId string `protobuf:"bytes,5,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// Absolute issuance time (truncated to seconds).
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintBootstrapTokenResponse) Reset() {
	*x = MintBootstrapTokenResponse{}
	mi := &file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintBootstrapTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintBootstrapTokenResponse) ProtoMessage() {}

func (x *MintBootstrapTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintBootstrapTokenResponse.ProtoReflect.Descriptor instead.
func (*MintBootstrapTokenResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescGZIP(), []int{1}
}

func (x *MintBootstrapTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *MintBootstrapTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *MintBootstrapTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *MintBootstrapTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *MintBootstrapTokenResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *MintBootstrapTokenResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDesc = "" +
	"\n" +
	":kaname/cloud/iam/v1/internal_bootstrap_token_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(kaname/cloud/iam/v1/secret_options.proto\x1a$corelib/authz/v1/authz_options.proto\".\n" +
	"\x19MintBootstrapTokenRequestJ\x04\b\x01\x10\x02R\vttl_seconds\"\x9a\x02\n" +
	"\x1aMintBootstrapTokenResponse\x12'\n" +
	"\faccess_token\x18\x01 \x01(\tB\x04\xc0\xc81\x01R\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\fprincipal_id\x18\x05 \x01(\tR\vprincipalId\x127\n" +
	"\tissued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt2\xba\x01\n" +
	"\x1dInternalBootstrapTokenService\x12\x98\x01\n" +
	"\x12MintBootstrapToken\x12..kaname.cloud.iam.v1.MintBootstrapTokenRequest\x1a/.kaname.cloud.iam.v1.MintBootstrapTokenResponse\"!\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x11INTERNAL_LISTENERBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_goTypes = []any{
	(*MintBootstrapTokenRequest)(nil),  // 0: kaname.cloud.iam.v1.MintBootstrapTokenRequest
	(*MintBootstrapTokenResponse)(nil), // 1: kaname.cloud.iam.v1.MintBootstrapTokenResponse
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_depIdxs = []int32{
	2, // 0: kaname.cloud.iam.v1.MintBootstrapTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	2, // 1: kaname.cloud.iam.v1.MintBootstrapTokenResponse.issued_at:type_name -> google.protobuf.Timestamp
	0, // 2: kaname.cloud.iam.v1.InternalBootstrapTokenService.MintBootstrapToken:input_type -> kaname.cloud.iam.v1.MintBootstrapTokenRequest
	1, // 3: kaname.cloud.iam.v1.InternalBootstrapTokenService.MintBootstrapToken:output_type -> kaname.cloud.iam.v1.MintBootstrapTokenResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_init() }
func file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_init() {
	if File_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_secret_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto = out.File
	file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_internal_bootstrap_token_service_proto_depIdxs = nil
}
