// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/internal_limit_service.proto

// InternalLimitService — Internal-only.
// Registered exclusively on the api-gateway internal mux (cluster-internal
// listener) under `/iam/v1/internal/limits`; never on the external TLS endpoint
// (ban #6). The dispatcher — not the absence of a route — is what keeps it
// outside: `isInternalRoute` is keyed on the (method, path) pair and answers 404
// for external origin, hiding existence.
//
// WHAT IT MANAGES. The ceiling on how many resources of one kind a tenant may
// hold. Assigning one is an administrative act about a tenant's share of a shared
// platform, and there is no tenant-facing subject in "how large may your ceiling
// be" — the tenant reads its OWN effective ceiling and consumption from the owner
// of the resource type, not from here.
//
// TWO AUDIENCES, TWO GATES. The five CRUD verbs are ADMIN surface, fronted by the
// api-gateway on behalf of an operator: `system_admin` on the cluster object. The
// two read verbs below them — `Resolve` and `ListChangedSince` — are SERVICE
// surface, dialled by the owner services that do the counting, and they carry a
// NARROW relation of their own (`quota_reader`) rather than the cluster read
// tier. The distinction is least-privilege, not taxonomy: `system_viewer` would
// hand an owner service the whole cluster-scoped read surface to learn two
// numbers, and a relation satisfiable by a wildcard tuple would hand it to every
// authenticated tenant (security.md §«Отношение, выполнимое подстановочным
// знаком»).
//
// AUTHENTICATION FLOOR. `Create` / `Update` / `Delete` declare
// `required_acr_min = "2"`: raising or lowering a ceiling changes what a tenant
// may do to a shared resource. The four reads declare `"1"`. Every RPC declares
// its floor EXPLICITLY, because the generator's default is "2" and an unstated
// floor would arrive as sensitive by accident rather than by decision.
//
// ASYNC CONTRACT. Mutations return `Operation` (ban #9); `done` means the subject
// of the mutation is durable and is never gated on the visibility of anything
// downstream — an owner's projection catches up by pulling the delta.

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/api/v1"
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Limit to return. Form `lim-<17 crockford-base32>` (21 chars).
	LimitId       string `protobuf:"bytes,1,opt,name=limit_id,json=limitId,proto3" json:"limit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitRequest) Reset() {
	*x = GetLimitRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitRequest) ProtoMessage() {}

func (x *GetLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitRequest.ProtoReflect.Descriptor instead.
func (*GetLimitRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetLimitRequest) GetLimitId() string {
	if x != nil {
		return x.LimitId
	}
	return ""
}

type ListLimitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of results per page. 0 → default; >1000 is REJECTED,
	// not clamped (api-conventions).
	PageSize int64 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor from a previous response.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Narrow to one scope. SCOPE_UNSPECIFIED → every scope.
	Scope Limit_Scope `protobuf:"varint,3,opt,name=scope,proto3,enum=kaname.cloud.iam.v1.Limit_Scope" json:"scope,omitempty"`
	// Narrow to the limits stated for one account / project. Empty → no narrowing
	// by object. Supplying it WITHOUT `scope` is legal and means "wherever this
	// object is named".
	ScopeId string `protobuf:"bytes,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// Narrow to one kind. Empty → every kind.
	//
	// The three narrowing fields are typed request fields rather than a filter
	// expression on purpose: the vocabulary here is closed and three-valued, and a
	// parser would introduce a second grammar whose only job is to be told the same
	// three things.
	Kind          string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLimitsRequest) Reset() {
	*x = ListLimitsRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLimitsRequest) ProtoMessage() {}

func (x *ListLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLimitsRequest.ProtoReflect.Descriptor instead.
func (*ListLimitsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListLimitsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLimitsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListLimitsRequest) GetScope() Limit_Scope {
	if x != nil {
		return x.Scope
	}
	return Limit_SCOPE_UNSPECIFIED
}

func (x *ListLimitsRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ListLimitsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListLimitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The page of limits.
	Limits []*Limit `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	// Cursor for the next page; empty when the page is the last one.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLimitsResponse) Reset() {
	*x = ListLimitsResponse{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLimitsResponse) ProtoMessage() {}

func (x *ListLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLimitsResponse.ProtoReflect.Descriptor instead.
func (*ListLimitsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListLimitsResponse) GetLimits() []*Limit {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ListLimitsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scope this limit is stated at. Required — SCOPE_UNSPECIFIED is refused by
	// name rather than defaulted, because every default here would be a guess
	// about the blast radius of the ceiling.
	Scope Limit_Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=kaname.cloud.iam.v1.Limit_Scope" json:"scope,omitempty"`
	// Id of the account (ACCOUNT) or project (PROJECT) the scope names. MUST be
	// empty for DEFAULT and non-empty otherwise; the pairing is refused by name.
	ScopeId string `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// Kind this limit governs. Must be a member of the platform's closed
	// catalogue of countable kinds.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// The ceiling. Zero is legal ("none of this kind"); negative is refused by
	// name.
	Value         int64 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLimitRequest) Reset() {
	*x = CreateLimitRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLimitRequest) ProtoMessage() {}

func (x *CreateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLimitRequest.ProtoReflect.Descriptor instead.
func (*CreateLimitRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLimitRequest) GetScope() Limit_Scope {
	if x != nil {
		return x.Scope
	}
	return Limit_SCOPE_UNSPECIFIED
}

func (x *CreateLimitRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *CreateLimitRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateLimitRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Limit to update.
	LimitId string `protobuf:"bytes,1,opt,name=limit_id,json=limitId,proto3" json:"limit_id,omitempty"`
	// Fields to update. Empty mask → full-object PATCH over mutable fields;
	// immutable fields present in the body are silently ignored. A mask naming an
	// immutable field is rejected BY NAME; a mask naming an unknown field is
	// rejected against the known-set.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The new ceiling.
	Value         int64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitRequest) Reset() {
	*x = UpdateLimitRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitRequest) ProtoMessage() {}

func (x *UpdateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitRequest.ProtoReflect.Descriptor instead.
func (*UpdateLimitRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLimitRequest) GetLimitId() string {
	if x != nil {
		return x.LimitId
	}
	return ""
}

func (x *UpdateLimitRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateLimitRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DeleteLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Limit to withdraw.
	LimitId       string `protobuf:"bytes,1,opt,name=limit_id,json=limitId,proto3" json:"limit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLimitRequest) Reset() {
	*x = DeleteLimitRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLimitRequest) ProtoMessage() {}

func (x *DeleteLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLimitRequest.ProtoReflect.Descriptor instead.
func (*DeleteLimitRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLimitRequest) GetLimitId() string {
	if x != nil {
		return x.LimitId
	}
	return ""
}

type ResolveLimitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the object the ceilings are wanted for: a project id (the usual case)
	// or an account id. The kind of object is established by LOOKING IT UP, never
	// by reading its prefix — a prefix is a routing hint, not a statement about
	// what exists.
	ScopeId string `protobuf:"bytes,1,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	// Service whose kinds are wanted (`vpc`, `iam`, …). The answer carries one row
	// per kind that service owns, so the caller never has to know which kinds
	// exist — that catalogue is the platform's, not the caller's copy of it.
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLimitsRequest) Reset() {
	*x = ResolveLimitsRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLimitsRequest) ProtoMessage() {}

func (x *ResolveLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLimitsRequest.ProtoReflect.Descriptor instead.
func (*ResolveLimitsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveLimitsRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ResolveLimitsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ResolveLimitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per kind of the requested service, in the catalogue's order.
	Limits        []*EffectiveLimit `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLimitsResponse) Reset() {
	*x = ResolveLimitsResponse{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLimitsResponse) ProtoMessage() {}

func (x *ResolveLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLimitsResponse.ProtoReflect.Descriptor instead.
func (*ResolveLimitsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveLimitsResponse) GetLimits() []*EffectiveLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ListChangedLimitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque cursor from a previous response. Empty → from the beginning of time,
	// which is what a projection that has never synchronised needs.
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// The maximum number of entries per page. 0 → default; >1000 is REJECTED.
	PageSize      int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangedLimitsRequest) Reset() {
	*x = ListChangedLimitsRequest{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangedLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangedLimitsRequest) ProtoMessage() {}

func (x *ListChangedLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangedLimitsRequest.ProtoReflect.Descriptor instead.
func (*ListChangedLimitsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListChangedLimitsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListChangedLimitsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChangedLimitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entries whose revision is greater than the cursor, in revision order.
	Changes []*LimitChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	// Cursor to pass next time. Always returned, INCLUDING on an empty page: a
	// puller that only advanced on non-empty pages would re-scan the same tail
	// forever once it caught up.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangedLimitsResponse) Reset() {
	*x = ListChangedLimitsResponse{}
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangedLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangedLimitsResponse) ProtoMessage() {}

func (x *ListChangedLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangedLimitsResponse.ProtoReflect.Descriptor instead.
func (*ListChangedLimitsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListChangedLimitsResponse) GetChanges() []*LimitChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ListChangedLimitsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_kaname_cloud_iam_v1_internal_limit_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDesc = "" +
	"\n" +
	"0kaname/cloud/iam/v1/internal_limit_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1ecorelib/api/v1/operation.proto\x1a\x1fkaname/cloud/iam/v1/limit.proto\x1a%kacho/cloud/operation/operation.proto\x1a$corelib/authz/v1/authz_options.proto\",\n" +
	"\x0fGetLimitRequest\x12\x19\n" +
	"\blimit_id\x18\x01 \x01(\tR\alimitId\"\xb6\x01\n" +
	"\x11ListLimitsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x126\n" +
	"\x05scope\x18\x03 \x01(\x0e2 .kaname.cloud.iam.v1.Limit.ScopeR\x05scope\x12\x19\n" +
	"\bscope_id\x18\x04 \x01(\tR\ascopeId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"p\n" +
	"\x12ListLimitsResponse\x122\n" +
	"\x06limits\x18\x01 \x03(\v2\x1a.kaname.cloud.iam.v1.LimitR\x06limits\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x91\x01\n" +
	"\x12CreateLimitRequest\x126\n" +
	"\x05scope\x18\x01 \x01(\x0e2 .kaname.cloud.iam.v1.Limit.ScopeR\x05scope\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\"\x82\x01\n" +
	"\x12UpdateLimitRequest\x12\x19\n" +
	"\blimit_id\x18\x01 \x01(\tR\alimitId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"/\n" +
	"\x12DeleteLimitRequest\x12\x19\n" +
	"\blimit_id\x18\x01 \x01(\tR\alimitId\"K\n" +
	"\x14ResolveLimitsRequest\x12\x19\n" +
	"\bscope_id\x18\x01 \x01(\tR\ascopeId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"T\n" +
	"\x15ResolveLimitsResponse\x12;\n" +
	"\x06limits\x18\x01 \x03(\v2#.kaname.cloud.iam.v1.EffectiveLimitR\x06limits\"O\n" +
	"\x18ListChangedLimitsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"x\n" +
	"\x19ListChangedLimitsResponse\x12:\n" +
	"\achanges\x18\x01 \x03(\v2 .kaname.cloud.iam.v1.LimitChangeR\achanges\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xb4\v\n" +
	"\x14InternalLimitService\x12\xaa\x01\n" +
	"\x03Get\x12$.kaname.cloud.iam.v1.GetLimitRequest\x1a\x1a.kaname.cloud.iam.v1.Limit\"a\x8a\xb5\x18\x0eiam.limits.get\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02$\x12\"/iam/v1/internal/limits/{limit_id}\x12\xb0\x01\n" +
	"\x04List\x12&.kaname.cloud.iam.v1.ListLimitsRequest\x1a'.kaname.cloud.iam.v1.ListLimitsResponse\"W\x8a\xb5\x18\x0fiam.limits.list\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x19\x12\x17/iam/v1/internal/limits\x12\xd1\x01\n" +
	"\x06Create\x12'.kaname.cloud.iam.v1.CreateLimitRequest\x1a .kacho.cloud.operation.Operation\"|\x8a\xb5\x18\x11iam.limits.create\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x012\xb2\xd2*\x1c\n" +
	"\x13CreateLimitMetadata\x12\x05Limit\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/iam/v1/internal/limits\x12\xdd\x01\n" +
	"\x06Update\x12'.kaname.cloud.iam.v1.UpdateLimitRequest\x1a .kacho.cloud.operation.Operation\"\x87\x01\x8a\xb5\x18\x11iam.limits.update\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x012\xb2\xd2*\x1c\n" +
	"\x13UpdateLimitMetadata\x12\x05Limit\x82\xd3\xe4\x93\x02':\x01*2\"/iam/v1/internal/limits/{limit_id}\x12\xda\x01\n" +
	"\x06Delete\x12'.kaname.cloud.iam.v1.DeleteLimitRequest\x1a .kacho.cloud.operation.Operation\"\x84\x01\x8a\xb5\x18\x11iam.limits.delete\x92\xb5\x18\fsystem_admin\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x012\xb2\xd2*\x1c\n" +
	"\x13DeleteLimitMetadata\x12\x05Limit\x82\xd3\xe4\x93\x02$*\"/iam/v1/internal/limits/{limit_id}\x12\xc4\x01\n" +
	"\aResolve\x12).kaname.cloud.iam.v1.ResolveLimitsRequest\x1a*.kaname.cloud.iam.v1.ResolveLimitsResponse\"b\x8a\xb5\x18\x12iam.limits.resolve\x92\xb5\x18\fquota_reader\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02!\x12\x1f/iam/v1/internal/limits:resolve\x12\xe3\x01\n" +
	"\x10ListChangedSince\x12-.kaname.cloud.iam.v1.ListChangedLimitsRequest\x1a..kaname.cloud.iam.v1.ListChangedLimitsResponse\"p\x8a\xb5\x18\x1biam.limits.listChangedSince\x92\xb5\x18\fquota_reader\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02&\x12$/iam/v1/internal/limits:changedSinceBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kaname_cloud_iam_v1_internal_limit_service_proto_goTypes = []any{
	(*GetLimitRequest)(nil),           // 0: kaname.cloud.iam.v1.GetLimitRequest
	(*ListLimitsRequest)(nil),         // 1: kaname.cloud.iam.v1.ListLimitsRequest
	(*ListLimitsResponse)(nil),        // 2: kaname.cloud.iam.v1.ListLimitsResponse
	(*CreateLimitRequest)(nil),        // 3: kaname.cloud.iam.v1.CreateLimitRequest
	(*UpdateLimitRequest)(nil),        // 4: kaname.cloud.iam.v1.UpdateLimitRequest
	(*DeleteLimitRequest)(nil),        // 5: kaname.cloud.iam.v1.DeleteLimitRequest
	(*ResolveLimitsRequest)(nil),      // 6: kaname.cloud.iam.v1.ResolveLimitsRequest
	(*ResolveLimitsResponse)(nil),     // 7: kaname.cloud.iam.v1.ResolveLimitsResponse
	(*ListChangedLimitsRequest)(nil),  // 8: kaname.cloud.iam.v1.ListChangedLimitsRequest
	(*ListChangedLimitsResponse)(nil), // 9: kaname.cloud.iam.v1.ListChangedLimitsResponse
	(Limit_Scope)(0),                  // 10: kaname.cloud.iam.v1.Limit.Scope
	(*Limit)(nil),                     // 11: kaname.cloud.iam.v1.Limit
	(*fieldmaskpb.FieldMask)(nil),     // 12: google.protobuf.FieldMask
	(*EffectiveLimit)(nil),            // 13: kaname.cloud.iam.v1.EffectiveLimit
	(*LimitChange)(nil),               // 14: kaname.cloud.iam.v1.LimitChange
	(*operation.Operation)(nil),       // 15: kacho.cloud.operation.Operation
}
var file_kaname_cloud_iam_v1_internal_limit_service_proto_depIdxs = []int32{
	10, // 0: kaname.cloud.iam.v1.ListLimitsRequest.scope:type_name -> kaname.cloud.iam.v1.Limit.Scope
	11, // 1: kaname.cloud.iam.v1.ListLimitsResponse.limits:type_name -> kaname.cloud.iam.v1.Limit
	10, // 2: kaname.cloud.iam.v1.CreateLimitRequest.scope:type_name -> kaname.cloud.iam.v1.Limit.Scope
	12, // 3: kaname.cloud.iam.v1.UpdateLimitRequest.update_mask:type_name -> google.protobuf.FieldMask
	13, // 4: kaname.cloud.iam.v1.ResolveLimitsResponse.limits:type_name -> kaname.cloud.iam.v1.EffectiveLimit
	14, // 5: kaname.cloud.iam.v1.ListChangedLimitsResponse.changes:type_name -> kaname.cloud.iam.v1.LimitChange
	0,  // 6: kaname.cloud.iam.v1.InternalLimitService.Get:input_type -> kaname.cloud.iam.v1.GetLimitRequest
	1,  // 7: kaname.cloud.iam.v1.InternalLimitService.List:input_type -> kaname.cloud.iam.v1.ListLimitsRequest
	3,  // 8: kaname.cloud.iam.v1.InternalLimitService.Create:input_type -> kaname.cloud.iam.v1.CreateLimitRequest
	4,  // 9: kaname.cloud.iam.v1.InternalLimitService.Update:input_type -> kaname.cloud.iam.v1.UpdateLimitRequest
	5,  // 10: kaname.cloud.iam.v1.InternalLimitService.Delete:input_type -> kaname.cloud.iam.v1.DeleteLimitRequest
	6,  // 11: kaname.cloud.iam.v1.InternalLimitService.Resolve:input_type -> kaname.cloud.iam.v1.ResolveLimitsRequest
	8,  // 12: kaname.cloud.iam.v1.InternalLimitService.ListChangedSince:input_type -> kaname.cloud.iam.v1.ListChangedLimitsRequest
	11, // 13: kaname.cloud.iam.v1.InternalLimitService.Get:output_type -> kaname.cloud.iam.v1.Limit
	2,  // 14: kaname.cloud.iam.v1.InternalLimitService.List:output_type -> kaname.cloud.iam.v1.ListLimitsResponse
	15, // 15: kaname.cloud.iam.v1.InternalLimitService.Create:output_type -> kacho.cloud.operation.Operation
	15, // 16: kaname.cloud.iam.v1.InternalLimitService.Update:output_type -> kacho.cloud.operation.Operation
	15, // 17: kaname.cloud.iam.v1.InternalLimitService.Delete:output_type -> kacho.cloud.operation.Operation
	7,  // 18: kaname.cloud.iam.v1.InternalLimitService.Resolve:output_type -> kaname.cloud.iam.v1.ResolveLimitsResponse
	9,  // 19: kaname.cloud.iam.v1.InternalLimitService.ListChangedSince:output_type -> kaname.cloud.iam.v1.ListChangedLimitsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_internal_limit_service_proto_init() }
func file_kaname_cloud_iam_v1_internal_limit_service_proto_init() {
	if File_kaname_cloud_iam_v1_internal_limit_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_limit_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_internal_limit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_internal_limit_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_internal_limit_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_internal_limit_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_internal_limit_service_proto = out.File
	file_kaname_cloud_iam_v1_internal_limit_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_internal_limit_service_proto_depIdxs = nil
}
