// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kaname/cloud/iam/v1/internal_limit_service.proto

// InternalLimitService — Internal-only.
// Registered exclusively on the api-gateway internal mux (cluster-internal
// listener) under `/iam/v1/internal/limits`; never on the external TLS endpoint
// (ban #6). The dispatcher — not the absence of a route — is what keeps it
// outside: `isInternalRoute` is keyed on the (method, path) pair and answers 404
// for external origin, hiding existence.
//
// WHAT IT MANAGES. The ceiling on how many resources of one kind a tenant may
// hold. Assigning one is an administrative act about a tenant's share of a shared
// platform, and there is no tenant-facing subject in "how large may your ceiling
// be" — the tenant reads its OWN effective ceiling and consumption from the owner
// of the resource type, not from here.
//
// TWO AUDIENCES, TWO GATES. The five CRUD verbs are ADMIN surface, fronted by the
// api-gateway on behalf of an operator: `system_admin` on the cluster object. The
// two read verbs below them — `Resolve` and `ListChangedSince` — are SERVICE
// surface, dialled by the owner services that do the counting, and they carry a
// NARROW relation of their own (`quota_reader`) rather than the cluster read
// tier. The distinction is least-privilege, not taxonomy: `system_viewer` would
// hand an owner service the whole cluster-scoped read surface to learn two
// numbers, and a relation satisfiable by a wildcard tuple would hand it to every
// authenticated tenant (security.md §«Отношение, выполнимое подстановочным
// знаком»).
//
// AUTHENTICATION FLOOR. `Create` / `Update` / `Delete` declare
// `required_acr_min = "2"`: raising or lowering a ceiling changes what a tenant
// may do to a shared resource. The four reads declare `"1"`. Every RPC declares
// its floor EXPLICITLY, because the generator's default is "2" and an unstated
// floor would arrive as sensitive by accident rather than by decision.
//
// ASYNC CONTRACT. Mutations return `Operation` (ban #9); `done` means the subject
// of the mutation is durable and is never gated on the visibility of anything
// downstream — an owner's projection catches up by pulling the delta.

package iamv1

import (
	context "context"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalLimitService_Get_FullMethodName              = "/kaname.cloud.iam.v1.InternalLimitService/Get"
	InternalLimitService_List_FullMethodName             = "/kaname.cloud.iam.v1.InternalLimitService/List"
	InternalLimitService_Create_FullMethodName           = "/kaname.cloud.iam.v1.InternalLimitService/Create"
	InternalLimitService_Update_FullMethodName           = "/kaname.cloud.iam.v1.InternalLimitService/Update"
	InternalLimitService_Delete_FullMethodName           = "/kaname.cloud.iam.v1.InternalLimitService/Delete"
	InternalLimitService_Resolve_FullMethodName          = "/kaname.cloud.iam.v1.InternalLimitService/Resolve"
	InternalLimitService_ListChangedSince_FullMethodName = "/kaname.cloud.iam.v1.InternalLimitService/ListChangedSince"
)

// InternalLimitServiceClient is the client API for InternalLimitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalLimitService — administration of resource-count ceilings plus the two
// reads owner-services live on. See the file-level comment for the gates.
type InternalLimitServiceClient interface {
	// Returns the requested Limit. Sync read; no Operation envelope.
	//
	// A malformed id is rejected synchronously as `INVALID_ARGUMENT` by the first
	// statement of the RPC; a well-formed id with no row is `NOT_FOUND` (direct-read
	// lane — this is iam's own resource).
	//
	// REST exposed ONLY on the cluster-internal listener.
	Get(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*Limit, error)
	// Lists Limits, optionally narrowed to one scope / scope object / kind. Sync
	// read, cursor-paginated on `(created_at, id)`.
	//
	// REST exposed ONLY on the cluster-internal listener.
	List(ctx context.Context, in *ListLimitsRequest, opts ...grpc.CallOption) (*ListLimitsResponse, error)
	// States a ceiling for one (scope, scope object, kind) triple.
	//
	// The triple is unique among the limits in force: a second Create on the same
	// triple is `ALREADY_EXISTS`, and that promise is a database constraint rather
	// than a read-then-write check, so two concurrent Creates produce one row and
	// one refusal.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Create(ctx context.Context, in *CreateLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Changes the ceiling. `value` is the only mutable field: the triple a limit
	// governs IS its identity, so "moving" a limit to another project or kind is a
	// different limit, created and withdrawn explicitly.
	//
	// Lowering a ceiling BELOW current consumption is legal and is the point: it
	// freezes creation while leaving what exists readable and deletable. A schema
	// that forbade the state would make the ordinary administrative act
	// inexpressible.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Update(ctx context.Context, in *UpdateLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Withdraws a ceiling. The triple falls back to the next scope; withdrawing a
	// DEFAULT leaves the kind with no ceiling stated anywhere, which owner services
	// treat as a refusal to guess rather than as "unbounded".
	//
	// Idempotent — withdrawing an already-withdrawn limit does not differ in code
	// from the first withdrawal.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Delete(ctx context.Context, in *DeleteLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Returns the ceilings in force for one scope object, for every kind one
	// service owns. Sync read; the owner service calls it when its own projection
	// has nothing to say about a tenant.
	//
	// Precedence is applied here, once: PROJECT over ACCOUNT over DEFAULT. Making
	// each owner re-implement the precedence would put the same three-way rule in
	// as many places as there are owners, and they would disagree the first time
	// one of them was extended.
	//
	// Gated by the narrow `quota_reader` relation — see the file-level comment.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Resolve(ctx context.Context, in *ResolveLimitsRequest, opts ...grpc.CallOption) (*ResolveLimitsResponse, error)
	// Returns limits whose value changed (or which were withdrawn) after the
	// caller's cursor. Sync read; this is how an owner keeps its projection fresh
	// without asking about every tenant it has ever seen.
	//
	// A write that restates the value a limit already had does NOT appear here: the
	// revision advances on CHANGE, so an idempotent re-assignment cannot make every
	// puller re-read the world.
	//
	// Gated by the narrow `quota_reader` relation — see the file-level comment.
	//
	// REST exposed ONLY on the cluster-internal listener.
	ListChangedSince(ctx context.Context, in *ListChangedLimitsRequest, opts ...grpc.CallOption) (*ListChangedLimitsResponse, error)
}

type internalLimitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalLimitServiceClient(cc grpc.ClientConnInterface) InternalLimitServiceClient {
	return &internalLimitServiceClient{cc}
}

func (c *internalLimitServiceClient) Get(ctx context.Context, in *GetLimitRequest, opts ...grpc.CallOption) (*Limit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Limit)
	err := c.cc.Invoke(ctx, InternalLimitService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) List(ctx context.Context, in *ListLimitsRequest, opts ...grpc.CallOption) (*ListLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLimitsResponse)
	err := c.cc.Invoke(ctx, InternalLimitService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) Create(ctx context.Context, in *CreateLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalLimitService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) Update(ctx context.Context, in *UpdateLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalLimitService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) Delete(ctx context.Context, in *DeleteLimitRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, InternalLimitService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) Resolve(ctx context.Context, in *ResolveLimitsRequest, opts ...grpc.CallOption) (*ResolveLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveLimitsResponse)
	err := c.cc.Invoke(ctx, InternalLimitService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalLimitServiceClient) ListChangedSince(ctx context.Context, in *ListChangedLimitsRequest, opts ...grpc.CallOption) (*ListChangedLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangedLimitsResponse)
	err := c.cc.Invoke(ctx, InternalLimitService_ListChangedSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalLimitServiceServer is the server API for InternalLimitService service.
// All implementations must embed UnimplementedInternalLimitServiceServer
// for forward compatibility.
//
// InternalLimitService — administration of resource-count ceilings plus the two
// reads owner-services live on. See the file-level comment for the gates.
type InternalLimitServiceServer interface {
	// Returns the requested Limit. Sync read; no Operation envelope.
	//
	// A malformed id is rejected synchronously as `INVALID_ARGUMENT` by the first
	// statement of the RPC; a well-formed id with no row is `NOT_FOUND` (direct-read
	// lane — this is iam's own resource).
	//
	// REST exposed ONLY on the cluster-internal listener.
	Get(context.Context, *GetLimitRequest) (*Limit, error)
	// Lists Limits, optionally narrowed to one scope / scope object / kind. Sync
	// read, cursor-paginated on `(created_at, id)`.
	//
	// REST exposed ONLY on the cluster-internal listener.
	List(context.Context, *ListLimitsRequest) (*ListLimitsResponse, error)
	// States a ceiling for one (scope, scope object, kind) triple.
	//
	// The triple is unique among the limits in force: a second Create on the same
	// triple is `ALREADY_EXISTS`, and that promise is a database constraint rather
	// than a read-then-write check, so two concurrent Creates produce one row and
	// one refusal.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Create(context.Context, *CreateLimitRequest) (*operation.Operation, error)
	// Changes the ceiling. `value` is the only mutable field: the triple a limit
	// governs IS its identity, so "moving" a limit to another project or kind is a
	// different limit, created and withdrawn explicitly.
	//
	// Lowering a ceiling BELOW current consumption is legal and is the point: it
	// freezes creation while leaving what exists readable and deletable. A schema
	// that forbade the state would make the ordinary administrative act
	// inexpressible.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Update(context.Context, *UpdateLimitRequest) (*operation.Operation, error)
	// Withdraws a ceiling. The triple falls back to the next scope; withdrawing a
	// DEFAULT leaves the kind with no ceiling stated anywhere, which owner services
	// treat as a refusal to guess rather than as "unbounded".
	//
	// Idempotent — withdrawing an already-withdrawn limit does not differ in code
	// from the first withdrawal.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Delete(context.Context, *DeleteLimitRequest) (*operation.Operation, error)
	// Returns the ceilings in force for one scope object, for every kind one
	// service owns. Sync read; the owner service calls it when its own projection
	// has nothing to say about a tenant.
	//
	// Precedence is applied here, once: PROJECT over ACCOUNT over DEFAULT. Making
	// each owner re-implement the precedence would put the same three-way rule in
	// as many places as there are owners, and they would disagree the first time
	// one of them was extended.
	//
	// Gated by the narrow `quota_reader` relation — see the file-level comment.
	//
	// REST exposed ONLY on the cluster-internal listener.
	Resolve(context.Context, *ResolveLimitsRequest) (*ResolveLimitsResponse, error)
	// Returns limits whose value changed (or which were withdrawn) after the
	// caller's cursor. Sync read; this is how an owner keeps its projection fresh
	// without asking about every tenant it has ever seen.
	//
	// A write that restates the value a limit already had does NOT appear here: the
	// revision advances on CHANGE, so an idempotent re-assignment cannot make every
	// puller re-read the world.
	//
	// Gated by the narrow `quota_reader` relation — see the file-level comment.
	//
	// REST exposed ONLY on the cluster-internal listener.
	ListChangedSince(context.Context, *ListChangedLimitsRequest) (*ListChangedLimitsResponse, error)
	mustEmbedUnimplementedInternalLimitServiceServer()
}

// UnimplementedInternalLimitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalLimitServiceServer struct{}

func (UnimplementedInternalLimitServiceServer) Get(context.Context, *GetLimitRequest) (*Limit, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInternalLimitServiceServer) List(context.Context, *ListLimitsRequest) (*ListLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInternalLimitServiceServer) Create(context.Context, *CreateLimitRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInternalLimitServiceServer) Update(context.Context, *UpdateLimitRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedInternalLimitServiceServer) Delete(context.Context, *DeleteLimitRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedInternalLimitServiceServer) Resolve(context.Context, *ResolveLimitsRequest) (*ResolveLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedInternalLimitServiceServer) ListChangedSince(context.Context, *ListChangedLimitsRequest) (*ListChangedLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChangedSince not implemented")
}
func (UnimplementedInternalLimitServiceServer) mustEmbedUnimplementedInternalLimitServiceServer() {}
func (UnimplementedInternalLimitServiceServer) testEmbeddedByValue()                              {}

// UnsafeInternalLimitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalLimitServiceServer will
// result in compilation errors.
type UnsafeInternalLimitServiceServer interface {
	mustEmbedUnimplementedInternalLimitServiceServer()
}

func RegisterInternalLimitServiceServer(s grpc.ServiceRegistrar, srv InternalLimitServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalLimitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalLimitService_ServiceDesc, srv)
}

func _InternalLimitService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).Get(ctx, req.(*GetLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).List(ctx, req.(*ListLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).Create(ctx, req.(*CreateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).Update(ctx, req.(*UpdateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).Delete(ctx, req.(*DeleteLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).Resolve(ctx, req.(*ResolveLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalLimitService_ListChangedSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangedLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalLimitServiceServer).ListChangedSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalLimitService_ListChangedSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalLimitServiceServer).ListChangedSince(ctx, req.(*ListChangedLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalLimitService_ServiceDesc is the grpc.ServiceDesc for InternalLimitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalLimitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaname.cloud.iam.v1.InternalLimitService",
	HandlerType: (*InternalLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _InternalLimitService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _InternalLimitService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _InternalLimitService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _InternalLimitService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _InternalLimitService_Delete_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _InternalLimitService_Resolve_Handler,
		},
		{
			MethodName: "ListChangedSince",
			Handler:    _InternalLimitService_ListChangedSince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kaname/cloud/iam/v1/internal_limit_service.proto",
}
