// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/permission_catalog_service.proto

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListPermissionCatalogRequest is empty — the catalog is the whole grantable
// taxonomy with no parameters (no id / filter / pagination in v1).
type ListPermissionCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionCatalogRequest) Reset() {
	*x = ListPermissionCatalogRequest{}
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionCatalogRequest) ProtoMessage() {}

func (x *ListPermissionCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionCatalogRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP(), []int{0}
}

// ListPermissionCatalogResponse is the flat, sync grantable taxonomy
// (camelCase on the wire).
type ListPermissionCatalogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of grantable modules (the 1st token segment), derived from the
	// keys of backend `objectTypes` (e.g. iam, vpc, compute, loadbalancer).
	// Deterministic order.
	Modules []*CatalogModule `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	// Набор глаголов, ОБЩИЙ ДЛЯ ВСЕХ ресурсов: пересечение наборов всех типов.
	// Порядок канонический и фиксированный — он часть контракта поля.
	//
	// ЭТО ПОЛЕ БОЛЬШЕ НЕ СЛОВАРЬ РЕДАКТОРА РОЛЕЙ. Набор глаголов — атрибут ТИПА, и
	// спрашивать его надо у ресурса: `CatalogResource.verbs`. Пересечение остаётся
	// как совместимость с уже написанными клиентами и как честный ответ на вопрос
	// «что даёт ЛЮБОЙ ресурс», но строить из него выпадающий список нельзя ни в
	// одну сторону: у ресурса с более широким набором глагол не предлагался бы,
	// хотя энфорсится, а сужение набора у ОДНОГО ресурса вынимало бы глагол из
	// списка у всех остальных (#1128).
	//
	// Поле поэтому СУЖАЕТСЯ по мере того, как наборы типов расходятся, и это его
	// объявленное поведение, а не поломка.
	ClosedVerbs []string `protobuf:"bytes,2,rep,name=closed_verbs,json=closedVerbs,proto3" json:"closed_verbs,omitempty"`
	// Platform-wide wildcard policy flags.
	WildcardPolicy *WildcardPolicy `protobuf:"bytes,3,opt,name=wildcard_policy,json=wildcardPolicy,proto3" json:"wildcard_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPermissionCatalogResponse) Reset() {
	*x = ListPermissionCatalogResponse{}
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionCatalogResponse) ProtoMessage() {}

func (x *ListPermissionCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionCatalogResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPermissionCatalogResponse) GetModules() []*CatalogModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ListPermissionCatalogResponse) GetClosedVerbs() []string {
	if x != nil {
		return x.ClosedVerbs
	}
	return nil
}

func (x *ListPermissionCatalogResponse) GetWildcardPolicy() *WildcardPolicy {
	if x != nil {
		return x.WildcardPolicy
	}
	return nil
}

// CatalogModule is a grantable module and the resources grantable within it.
type CatalogModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name (1st token segment, e.g. "vpc"), as in backend `objectTypes`.
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Resources grantable within this module.
	Resources     []*CatalogResource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogModule) Reset() {
	*x = CatalogModule{}
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogModule) ProtoMessage() {}

func (x *CatalogModule) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogModule.ProtoReflect.Descriptor instead.
func (*CatalogModule) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP(), []int{2}
}

func (x *CatalogModule) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CatalogModule) GetResources() []*CatalogResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// CatalogResource is one grantable `(module,resource)` token plus the editor
// flags the role-rule editor needs.
type CatalogResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name (2nd token segment), spelled EXACTLY as in backend
	// `objectTypes` (e.g. "securityGroup"/"routeTable"/"networkInterface", or the
	// loadbalancer plural tokens "networkLoadBalancers"/"targetGroups"/
	// "listeners"). The token travels on the wire as-is, never renamed.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// True for verb-bearing leaf types; false for tier-only ancestors
	// (iam.account / iam.project). Mirrors
	// `authzmap.TypeHasVerbRelations(objectType)`. A false value means
	// ARM_ANCHOR/ARM_LABELS rules on this type fail-closed-SKIP — access is
	// expressed via ARM_NAMES / tier roles.
	HasVerbRelations bool `protobuf:"varint,2,opt,name=has_verb_relations,json=hasVerbRelations,proto3" json:"has_verb_relations,omitempty"`
	// True if this type has a PUBLIC per-object filtered `List` registered on the
	// api-gateway EXTERNAL listener — the resourceNames picker then
	// renders a Select of caller-visible instances. False when there is no public
	// List, or the List exists only on the cluster-internal listener (:9091) —
	// the picker then falls back to a free-text input. The value is
	// taken from a closed backend table ("(module,resource) → public List?"), not
	// guessed by the UI. Internal-only List does NOT count as public.
	HasListEndpoint bool `protobuf:"varint,3,opt,name=has_list_endpoint,json=hasListEndpoint,proto3" json:"has_list_endpoint,omitempty"`
	// True if the type may carry a match_labels (ARM_LABELS) selector — it is in
	// the label-selectable feed set (kaname domain.IsLabelSelectableType:
	// mirror-fed types + iam.project/iam.account). ARM_NAMES (resourceNames) is
	// NOT feed-gated — any type may be pinned by id. The editor must NOT offer a
	// match_labels arm on a type where this is false (the rule compiler
	// fail-closed-rejects an ARM_LABELS rule on a non-label-selectable type with
	// INVALID_ARGUMENT "type %s is not selectable (no resource feed)"). E.g.
	// vpc.addressPool is grantable+verb-bearing but NOT label-selectable.
	LabelSelectable bool `protobuf:"varint,4,opt,name=label_selectable,json=labelSelectable,proto3" json:"label_selectable,omitempty"`
	// Глаголы, которые правило роли вправе назвать НА ЭТОМ ресурсе, в каноническом
	// порядке показа (`get`,`list`,`create`,`update`,`delete`, далее по алфавиту).
	// Зеркало набора, объявленного типом в канонической модели прав; пусто ровно
	// тогда, когда `has_verb_relations` = false.
	//
	// ЭТО — ИСТОЧНИК ВЫПАДАЮЩЕГО СПИСКА редактора ролей, а не `closed_verbs`
	// (#1128). Набор глаголов принадлежит ТИПУ: `loadbalancer.targetGroups` несёт
	// сверх обычного `addTargets`/`removeTargets`, `registry.registries` — `create`,
	// а у `iam.user` `update` снят (правку записи спрашивает другое отношение).
	// Общее пересечение не выражает ни одного из этих трёх случаев: из него
	// широкий глагол выпадает, а сужение у одного ресурса отнимает глагол у всех.
	//
	// Правило, назвавшее глагол ВНЕ этого набора, не даёт на этом типе ничего:
	// материализация сверяется с тем же набором и молча его отбрасывает. Поэтому
	// редактор обязан предлагать именно его — иначе роль авторуется в форме,
	// которая ничего не значит.
	Verbs         []string `protobuf:"bytes,5,rep,name=verbs,proto3" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogResource) Reset() {
	*x = CatalogResource{}
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogResource) ProtoMessage() {}

func (x *CatalogResource) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogResource.ProtoReflect.Descriptor instead.
func (*CatalogResource) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP(), []int{3}
}

func (x *CatalogResource) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CatalogResource) GetHasVerbRelations() bool {
	if x != nil {
		return x.HasVerbRelations
	}
	return false
}

func (x *CatalogResource) GetHasListEndpoint() bool {
	if x != nil {
		return x.HasListEndpoint
	}
	return false
}

func (x *CatalogResource) GetLabelSelectable() bool {
	if x != nil {
		return x.LabelSelectable
	}
	return false
}

func (x *CatalogResource) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// WildcardPolicy carries the catalog's wildcard policy flags, in parity with
// the rule-compiler enforcement — one source of policy truth.
type WildcardPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True: verb-`*` is grantable in a custom role (bounded "all verbs of the
	// type"). The editor renders the verb-`*` option enabled for custom.
	VerbWildcardAllowedCustom bool `protobuf:"varint,1,opt,name=verb_wildcard_allowed_custom,json=verbWildcardAllowedCustom,proto3" json:"verb_wildcard_allowed_custom,omitempty"`
	// True: module-`*` AND resource-`*` are system-only — using them in a custom
	// role yields INVALID_ARGUMENT. The editor renders module/resource-`*`
	// disabled for custom. (One flag covers both module and resource wildcards;
	// they share the system-only policy.)
	ModuleResourceWildcardSystemOnly bool `protobuf:"varint,2,opt,name=module_resource_wildcard_system_only,json=moduleResourceWildcardSystemOnly,proto3" json:"module_resource_wildcard_system_only,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *WildcardPolicy) Reset() {
	*x = WildcardPolicy{}
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildcardPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildcardPolicy) ProtoMessage() {}

func (x *WildcardPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildcardPolicy.ProtoReflect.Descriptor instead.
func (*WildcardPolicy) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP(), []int{4}
}

func (x *WildcardPolicy) GetVerbWildcardAllowedCustom() bool {
	if x != nil {
		return x.VerbWildcardAllowedCustom
	}
	return false
}

func (x *WildcardPolicy) GetModuleResourceWildcardSystemOnly() bool {
	if x != nil {
		return x.ModuleResourceWildcardSystemOnly
	}
	return false
}

var File_kaname_cloud_iam_v1_permission_catalog_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDesc = "" +
	"\n" +
	"4kaname/cloud/iam/v1/permission_catalog_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a$corelib/authz/v1/authz_options.proto\"\x1e\n" +
	"\x1cListPermissionCatalogRequest\"\xce\x01\n" +
	"\x1dListPermissionCatalogResponse\x12<\n" +
	"\amodules\x18\x01 \x03(\v2\".kaname.cloud.iam.v1.CatalogModuleR\amodules\x12!\n" +
	"\fclosed_verbs\x18\x02 \x03(\tR\vclosedVerbs\x12L\n" +
	"\x0fwildcard_policy\x18\x03 \x01(\v2#.kaname.cloud.iam.v1.WildcardPolicyR\x0ewildcardPolicy\"k\n" +
	"\rCatalogModule\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12B\n" +
	"\tresources\x18\x02 \x03(\v2$.kaname.cloud.iam.v1.CatalogResourceR\tresources\"\xc8\x01\n" +
	"\x0fCatalogResource\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12,\n" +
	"\x12has_verb_relations\x18\x02 \x01(\bR\x10hasVerbRelations\x12*\n" +
	"\x11has_list_endpoint\x18\x03 \x01(\bR\x0fhasListEndpoint\x12)\n" +
	"\x10label_selectable\x18\x04 \x01(\bR\x0flabelSelectable\x12\x14\n" +
	"\x05verbs\x18\x05 \x03(\tR\x05verbs\"\xa1\x01\n" +
	"\x0eWildcardPolicy\x12?\n" +
	"\x1cverb_wildcard_allowed_custom\x18\x01 \x01(\bR\x19verbWildcardAllowedCustom\x12N\n" +
	"$module_resource_wildcard_system_only\x18\x02 \x01(\bR moduleResourceWildcardSystemOnly2\xf5\x01\n" +
	"\x18PermissionCatalogService\x12\xd8\x01\n" +
	"\x15ListPermissionCatalog\x121.kaname.cloud.iam.v1.ListPermissionCatalogRequest\x1a2.kaname.cloud.iam.v1.ListPermissionCatalogResponse\"X\x8a\xb5\x18\x14iam.permissions.list\x92\xb5\x18\x06viewer\x9a\xb5\x18\f\n" +
	"\acluster\x12\x01*\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02\x1b\x12\x19/iam/v1/permissionCatalogBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kaname_cloud_iam_v1_permission_catalog_service_proto_goTypes = []any{
	(*ListPermissionCatalogRequest)(nil),  // 0: kaname.cloud.iam.v1.ListPermissionCatalogRequest
	(*ListPermissionCatalogResponse)(nil), // 1: kaname.cloud.iam.v1.ListPermissionCatalogResponse
	(*CatalogModule)(nil),                 // 2: kaname.cloud.iam.v1.CatalogModule
	(*CatalogResource)(nil),               // 3: kaname.cloud.iam.v1.CatalogResource
	(*WildcardPolicy)(nil),                // 4: kaname.cloud.iam.v1.WildcardPolicy
}
var file_kaname_cloud_iam_v1_permission_catalog_service_proto_depIdxs = []int32{
	2, // 0: kaname.cloud.iam.v1.ListPermissionCatalogResponse.modules:type_name -> kaname.cloud.iam.v1.CatalogModule
	4, // 1: kaname.cloud.iam.v1.ListPermissionCatalogResponse.wildcard_policy:type_name -> kaname.cloud.iam.v1.WildcardPolicy
	3, // 2: kaname.cloud.iam.v1.CatalogModule.resources:type_name -> kaname.cloud.iam.v1.CatalogResource
	0, // 3: kaname.cloud.iam.v1.PermissionCatalogService.ListPermissionCatalog:input_type -> kaname.cloud.iam.v1.ListPermissionCatalogRequest
	1, // 4: kaname.cloud.iam.v1.PermissionCatalogService.ListPermissionCatalog:output_type -> kaname.cloud.iam.v1.ListPermissionCatalogResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_permission_catalog_service_proto_init() }
func file_kaname_cloud_iam_v1_permission_catalog_service_proto_init() {
	if File_kaname_cloud_iam_v1_permission_catalog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_permission_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_permission_catalog_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_permission_catalog_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_permission_catalog_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_permission_catalog_service_proto = out.File
	file_kaname_cloud_iam_v1_permission_catalog_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_permission_catalog_service_proto_depIdxs = nil
}
