// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/role_service.proto

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/api/v1"
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Role resource to return.
	RoleId        string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of results per page to return. Default value: 100.
	PageSize int64 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// A filter expression. Supports filtering by is_system / name.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Scope the role catalog to a single Account.
	// When set, the response contains system roles (always visible, account_id is
	// empty) PLUS the custom roles owned by this Account — never another Account's
	// custom roles. Empty → unscoped catalog (subject to per-object visibility).
	AccountId     string `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListRolesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRolesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRolesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Role resources.
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// This token allows you to get the next page of results for list requests.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scope of the custom Role — EXACTLY ONE of account_id / project_id must be
	// set (request-level XOR; enforced by the service, since proto cannot express
	// it). account_id → an ACCOUNT-scoped role (assignable on its own account);
	// project_id → a PROJECT-scoped role (assignable on its own project,
	// project-anchor). System roles are seeded by migration, never via this RPC.
	//
	// No longer (required): a project-scoped role leaves account_id empty. The XOR
	// (account XOR project, both-empty and both-set → INVALID_ARGUMENT) is
	// enforced in the Role.Create use-case + DB CHECK `roles_scope_xor`.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Name of the role. 1-41 characters long.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the role.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// DEPRECATED: compiled-форма output-only. На входе
	// Create НЕ принимается (client-sent non-empty → INVALID_ARGUMENT). Tag
	// сохранен append-only; политика теперь авторится через `rules`.
	//
	// Deprecated: Marked as deprecated in kaname/cloud/iam/v1/role_service.proto.
	Permissions []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Authored-политика роли: 1..64 правил.
	// permissions[] на входе НЕ принимается — политика задается только здесь.
	Rules []*Rule `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	// ID of the Project that a PROJECT-scoped custom Role belongs to. Mutually
	// exclusive with account_id (XOR — see account_id). A project-scoped role is
	// assignable only on its OWN project (`project:<project_id>`, STRICT — no
	// hierarchy-down), unblocking the project-anchor materialization path.
	// The read-side Role message already carries project_id.
	ProjectId string `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Tenant-facing метки самого ресурса Role (НЕ путать с `Rule.match_labels`,
	// которое отбирает ОБЪЕКТЫ под грантом). Делают Role label-selectable
	// наравне с account/project. Аннотации (size/key/value pattern) — паритет
	// account/project/group request `labels`.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Definition tier (redesign-2026 F4) — the CANONICAL scope input, superseding the
	// legacy account_id/project_id pair: `tier_type` dotted (`iam.account` |
	// `iam.project`; `iam.cluster` rejected — system roles are seeded, not API-created)
	// + `tier_id` the anchor id. Pre-Phase-0 `tier_type` is REQUIRED (prefix-derivation
	// is B3-gated). When set it takes precedence; the legacy account_id/project_id are
	// still accepted for back-compat when definition_tier is omitted.
	DefinitionTier *DefinitionTier `protobuf:"bytes,8,opt,name=definition_tier,json=definitionTier,proto3" json:"definition_tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Deprecated: Marked as deprecated in kaname/cloud/iam/v1/role_service.proto.
func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateRoleRequest) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CreateRoleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateRoleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateRoleRequest) GetDefinitionTier() *DefinitionTier {
	if x != nil {
		return x.DefinitionTier
	}
	return nil
}

type UpdateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Role resource to update.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// Field mask. Allowed fields: name, description, rules, labels.
	// is_system / account_id / project_id / cluster_id / permissions (derived)
	// are immutable.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Name of the role.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the role.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// DEPRECATED: compiled-форма derived/immutable. В
	// update_mask → INVALID_ARGUMENT. Tag сохранен append-only.
	//
	// Deprecated: Marked as deprecated in kaname/cloud/iam/v1/role_service.proto.
	Permissions []string `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Authored-политика роли: 1..64 правил.
	// Применяется когда update_mask содержит `rules`.
	Rules []*Rule `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	// Optimistic-concurrency token (xmin-backed). Обязателен, когда update_mask
	// содержит `rules` (OCC под конкуренцией); mismatch →
	// FAILED_PRECONDITION.
	ResourceVersion string `protobuf:"bytes,7,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Tenant-facing метки самого ресурса Role (mutable; `labels` в update_mask).
	// НЕ путать с `Rule.match_labels`. Аннотации (size/key/value pattern) —
	// паритет account/project/group request `labels`.
	Labels        map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Deprecated: Marked as deprecated in kaname/cloud/iam/v1/role_service.proto.
func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateRoleRequest) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *UpdateRoleRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *UpdateRoleRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Role resource to delete.
	RoleId        string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type ListRoleOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Role resource to list operations for.
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// The maximum number of results per page that should be returned.
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleOperationsRequest) Reset() {
	*x = ListRoleOperationsRequest{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleOperationsRequest) ProtoMessage() {}

func (x *ListRoleOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListRoleOperationsRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoleOperationsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ListRoleOperationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRoleOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of operations for the specified role.
	Operations []*operation.Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	// This token allows you to get the next page of results for list requests.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleOperationsResponse) Reset() {
	*x = ListRoleOperationsResponse{}
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleOperationsResponse) ProtoMessage() {}

func (x *ListRoleOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_role_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleOperationsResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoleOperationsResponse) GetOperations() []*operation.Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListRoleOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_kaname_cloud_iam_v1_role_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_role_service_proto_rawDesc = "" +
	"\n" +
	"&kaname/cloud/iam/v1/role_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1ecorelib/api/v1/operation.proto\x1a\x1ekaname/cloud/iam/v1/role.proto\x1a%kacho/cloud/operation/operation.proto\x1a$corelib/authz/v1/authz_options.proto\")\n" +
	"\x0eGetRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x85\x01\n" +
	"\x10ListRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\"l\n" +
	"\x11ListRolesResponse\x12/\n" +
	"\x05roles\x18\x01 \x03(\v2\x19.kaname.cloud.iam.v1.RoleR\x05roles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb3\x03\n" +
	"\x11CreateRoleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\vpermissions\x18\x04 \x03(\tB\x02\x18\x01R\vpermissions\x12/\n" +
	"\x05rules\x18\x05 \x03(\v2\x19.kaname.cloud.iam.v1.RuleR\x05rules\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12J\n" +
	"\x06labels\x18\a \x03(\v22.kaname.cloud.iam.v1.CreateRoleRequest.LabelsEntryR\x06labels\x12L\n" +
	"\x0fdefinition_tier\x18\b \x01(\v2#.kaname.cloud.iam.v1.DefinitionTierR\x0edefinitionTier\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x03\n" +
	"\x11UpdateRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\vpermissions\x18\x05 \x03(\tB\x02\x18\x01R\vpermissions\x12/\n" +
	"\x05rules\x18\x06 \x03(\v2\x19.kaname.cloud.iam.v1.RuleR\x05rules\x12)\n" +
	"\x10resource_version\x18\a \x01(\tR\x0fresourceVersion\x12J\n" +
	"\x06labels\x18\b \x03(\v22.kaname.cloud.iam.v1.UpdateRoleRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x11DeleteRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"p\n" +
	"\x19ListRoleOperationsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x1aListRoleOperationsResponse\x12@\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2 .kacho.cloud.operation.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xfb\b\n" +
	"\vRoleService\x12{\n" +
	"\x03Get\x12#.kaname.cloud.iam.v1.GetRoleRequest\x1a\x19.kaname.cloud.iam.v1.Role\"4\x8a\xb5\x18\riam.roles.get\xb0\xb5\x18\x01\x82\xd3\xe4\x93\x02\x19\x12\x17/iam/v1/roles/{role_id}\x12\x82\x01\n" +
	"\x04List\x12%.kaname.cloud.iam.v1.ListRolesRequest\x1a&.kaname.cloud.iam.v1.ListRolesResponse\"+\x8a\xb5\x18\x0eiam.roles.list\xb0\xb5\x18\x01\x82\xd3\xe4\x93\x02\x0f\x12\r/iam/v1/roles\x12\xc6\x01\n" +
	"\x06Create\x12&.kaname.cloud.iam.v1.CreateRoleRequest\x1a .kacho.cloud.operation.Operation\"r\x8a\xb5\x18\x10iam.roles.create\x92\xb5\x18\x06editor\x9a\xb5\x18\x15\n" +
	"\aaccount\x12\n" +
	"account_id\xa2\xb5\x18\x011\xb2\xd2*\x1a\n" +
	"\x12CreateRoleMetadata\x12\x04Role\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/iam/v1/roles\x12\xd0\x01\n" +
	"\x06Update\x12&.kaname.cloud.iam.v1.UpdateRoleRequest\x1a .kacho.cloud.operation.Operation\"|\x8a\xb5\x18\x10iam.roles.update\x92\xb5\x18\bv_update\x9a\xb5\x18\x13\n" +
	"\biam_role\x12\arole_id\xa2\xb5\x18\x012\xb2\xd2*\x1a\n" +
	"\x12UpdateRoleMetadata\x12\x04Role\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/iam/v1/roles/{role_id}\x12\xdf\x01\n" +
	"\x06Delete\x12&.kaname.cloud.iam.v1.DeleteRoleRequest\x1a .kacho.cloud.operation.Operation\"\x8a\x01\x8a\xb5\x18\x10iam.roles.delete\x92\xb5\x18\bv_delete\x9a\xb5\x18\x13\n" +
	"\biam_role\x12\arole_id\xa2\xb5\x18\x012\xb2\xd2*+\n" +
	"\x12DeleteRoleMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02\x19*\x17/iam/v1/roles/{role_id}\x12\xeb\x01\n" +
	"\x0eListOperations\x12..kaname.cloud.iam.v1.ListRoleOperationsRequest\x1a/.kaname.cloud.iam.v1.ListRoleOperationsResponse\"x\x8a\xb5\x18$iam.role_operationses.listOperations\x92\xb5\x18\x06v_list\x9a\xb5\x18\x13\n" +
	"\biam_role\x12\arole_id\xa2\xb5\x18\x011\x82\xd3\xe4\x93\x02$\x12\"/iam/v1/roles/{role_id}/operationsBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_role_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_role_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_role_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_role_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_role_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_role_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_role_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_role_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_role_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kaname_cloud_iam_v1_role_service_proto_goTypes = []any{
	(*GetRoleRequest)(nil),             // 0: kaname.cloud.iam.v1.GetRoleRequest
	(*ListRolesRequest)(nil),           // 1: kaname.cloud.iam.v1.ListRolesRequest
	(*ListRolesResponse)(nil),          // 2: kaname.cloud.iam.v1.ListRolesResponse
	(*CreateRoleRequest)(nil),          // 3: kaname.cloud.iam.v1.CreateRoleRequest
	(*UpdateRoleRequest)(nil),          // 4: kaname.cloud.iam.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),          // 5: kaname.cloud.iam.v1.DeleteRoleRequest
	(*ListRoleOperationsRequest)(nil),  // 6: kaname.cloud.iam.v1.ListRoleOperationsRequest
	(*ListRoleOperationsResponse)(nil), // 7: kaname.cloud.iam.v1.ListRoleOperationsResponse
	nil,                                // 8: kaname.cloud.iam.v1.CreateRoleRequest.LabelsEntry
	nil,                                // 9: kaname.cloud.iam.v1.UpdateRoleRequest.LabelsEntry
	(*Role)(nil),                       // 10: kaname.cloud.iam.v1.Role
	(*Rule)(nil),                       // 11: kaname.cloud.iam.v1.Rule
	(*DefinitionTier)(nil),             // 12: kaname.cloud.iam.v1.DefinitionTier
	(*fieldmaskpb.FieldMask)(nil),      // 13: google.protobuf.FieldMask
	(*operation.Operation)(nil),        // 14: kacho.cloud.operation.Operation
}
var file_kaname_cloud_iam_v1_role_service_proto_depIdxs = []int32{
	10, // 0: kaname.cloud.iam.v1.ListRolesResponse.roles:type_name -> kaname.cloud.iam.v1.Role
	11, // 1: kaname.cloud.iam.v1.CreateRoleRequest.rules:type_name -> kaname.cloud.iam.v1.Rule
	8,  // 2: kaname.cloud.iam.v1.CreateRoleRequest.labels:type_name -> kaname.cloud.iam.v1.CreateRoleRequest.LabelsEntry
	12, // 3: kaname.cloud.iam.v1.CreateRoleRequest.definition_tier:type_name -> kaname.cloud.iam.v1.DefinitionTier
	13, // 4: kaname.cloud.iam.v1.UpdateRoleRequest.update_mask:type_name -> google.protobuf.FieldMask
	11, // 5: kaname.cloud.iam.v1.UpdateRoleRequest.rules:type_name -> kaname.cloud.iam.v1.Rule
	9,  // 6: kaname.cloud.iam.v1.UpdateRoleRequest.labels:type_name -> kaname.cloud.iam.v1.UpdateRoleRequest.LabelsEntry
	14, // 7: kaname.cloud.iam.v1.ListRoleOperationsResponse.operations:type_name -> kacho.cloud.operation.Operation
	0,  // 8: kaname.cloud.iam.v1.RoleService.Get:input_type -> kaname.cloud.iam.v1.GetRoleRequest
	1,  // 9: kaname.cloud.iam.v1.RoleService.List:input_type -> kaname.cloud.iam.v1.ListRolesRequest
	3,  // 10: kaname.cloud.iam.v1.RoleService.Create:input_type -> kaname.cloud.iam.v1.CreateRoleRequest
	4,  // 11: kaname.cloud.iam.v1.RoleService.Update:input_type -> kaname.cloud.iam.v1.UpdateRoleRequest
	5,  // 12: kaname.cloud.iam.v1.RoleService.Delete:input_type -> kaname.cloud.iam.v1.DeleteRoleRequest
	6,  // 13: kaname.cloud.iam.v1.RoleService.ListOperations:input_type -> kaname.cloud.iam.v1.ListRoleOperationsRequest
	10, // 14: kaname.cloud.iam.v1.RoleService.Get:output_type -> kaname.cloud.iam.v1.Role
	2,  // 15: kaname.cloud.iam.v1.RoleService.List:output_type -> kaname.cloud.iam.v1.ListRolesResponse
	14, // 16: kaname.cloud.iam.v1.RoleService.Create:output_type -> kacho.cloud.operation.Operation
	14, // 17: kaname.cloud.iam.v1.RoleService.Update:output_type -> kacho.cloud.operation.Operation
	14, // 18: kaname.cloud.iam.v1.RoleService.Delete:output_type -> kacho.cloud.operation.Operation
	7,  // 19: kaname.cloud.iam.v1.RoleService.ListOperations:output_type -> kaname.cloud.iam.v1.ListRoleOperationsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_role_service_proto_init() }
func file_kaname_cloud_iam_v1_role_service_proto_init() {
	if File_kaname_cloud_iam_v1_role_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_role_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_role_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_role_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_role_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_role_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_role_service_proto = out.File
	file_kaname_cloud_iam_v1_role_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_role_service_proto_depIdxs = nil
}
