// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/service_account.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A ServiceAccount resource. Machine-identity (non-human) субъект внутри Account.
//
// Текущая поверхность — только CRUD без key-credentials. Key-creds RPC (CreateKey/ListKeys через Ory Hydra
// client_credentials, OAuth2 token endpoint) появятся позже.
//
// Служебная учётка привязана к Account'у; `enabled` решает, вправе ли она
// аутентифицироваться.
//
// Resource id prefix: `sva` (concatenated form, `ids.NewID`).
type ServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the service account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the Account that this ServiceAccount belongs to.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Name of the service account. Unique within an Account. 1-63 characters long.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description of the service account.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Whether this ServiceAccount can authenticate. Defaults to true; toggle
	// false to disable without deletion.
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Tenant-facing метки. Единая модель видимости IAM-ресурсов: ServiceAccount —
	// label-selectable, как account/project; ARM_LABELS-грант на
	// iam.serviceAccount материализует глаголы своей роли на объектах, чьи `labels`
	// покрывают `matchLabels` (iam-direct same-DB), а страница List сужается тем же
	// отношением, которым каталог гейтит одиночное чтение — `v_get`; строка попадает
	// в выдачу ровно тогда, когда вызывающий вправе прочитать её по id.
	// Mutable через Update (`labels` в update_mask).
	Labels        map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceAccount) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateServiceAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ServiceAccount that is being created.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// ID of the owning Account (denormalized for account-scoped operations
	// listing — AccountService.ListAllOperations). Non-first field so the
	// corelib resource_id extractor (first `_id`-suffix match) still picks
	// `service_account_id`. Read by exact field name `account_id` by corelib.
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountMetadata) Reset() {
	*x = CreateServiceAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountMetadata) ProtoMessage() {}

func (x *CreateServiceAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountMetadata.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceAccountMetadata) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *CreateServiceAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateServiceAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ServiceAccount that is being updated.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// ID of the owning Account (denormalized; non-first, see CreateServiceAccountMetadata).
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceAccountMetadata) Reset() {
	*x = UpdateServiceAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountMetadata) ProtoMessage() {}

func (x *UpdateServiceAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountMetadata.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServiceAccountMetadata) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *UpdateServiceAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteServiceAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ServiceAccount that is being deleted.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// ID of the owning Account (denormalized; non-first, see CreateServiceAccountMetadata).
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceAccountMetadata) Reset() {
	*x = DeleteServiceAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountMetadata) ProtoMessage() {}

func (x *DeleteServiceAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountMetadata.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteServiceAccountMetadata) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *DeleteServiceAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DisableServiceAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ServiceAccount that is being disabled.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// ID of the owning Account (denormalized; non-first, see CreateServiceAccountMetadata).
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableServiceAccountMetadata) Reset() {
	*x = DisableServiceAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableServiceAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableServiceAccountMetadata) ProtoMessage() {}

func (x *DisableServiceAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableServiceAccountMetadata.ProtoReflect.Descriptor instead.
func (*DisableServiceAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{4}
}

func (x *DisableServiceAccountMetadata) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *DisableServiceAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type EnableServiceAccountMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ServiceAccount that is being enabled.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// ID of the owning Account (denormalized; non-first, see CreateServiceAccountMetadata).
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableServiceAccountMetadata) Reset() {
	*x = EnableServiceAccountMetadata{}
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableServiceAccountMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableServiceAccountMetadata) ProtoMessage() {}

func (x *EnableServiceAccountMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_service_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableServiceAccountMetadata.ProtoReflect.Descriptor instead.
func (*EnableServiceAccountMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP(), []int{5}
}

func (x *EnableServiceAccountMetadata) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *EnableServiceAccountMetadata) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_kaname_cloud_iam_v1_service_account_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_service_account_proto_rawDesc = "" +
	"\n" +
	")kaname/cloud/iam/v1/service_account.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x02\n" +
	"\x0eServiceAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12G\n" +
	"\x06labels\x18\b \x03(\v2/.kaname.cloud.iam.v1.ServiceAccount.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x06\x10\aR\n" +
	"project_id\"k\n" +
	"\x1cCreateServiceAccountMetadata\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"k\n" +
	"\x1cUpdateServiceAccountMetadata\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"k\n" +
	"\x1cDeleteServiceAccountMetadata\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"l\n" +
	"\x1dDisableServiceAccountMetadata\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"k\n" +
	"\x1cEnableServiceAccountMetadata\x12,\n" +
	"\x12service_account_id\x18\x01 \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountIdBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_service_account_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_service_account_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_service_account_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_service_account_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_service_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_service_account_proto_rawDesc), len(file_kaname_cloud_iam_v1_service_account_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_service_account_proto_rawDescData
}

var file_kaname_cloud_iam_v1_service_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kaname_cloud_iam_v1_service_account_proto_goTypes = []any{
	(*ServiceAccount)(nil),                // 0: kaname.cloud.iam.v1.ServiceAccount
	(*CreateServiceAccountMetadata)(nil),  // 1: kaname.cloud.iam.v1.CreateServiceAccountMetadata
	(*UpdateServiceAccountMetadata)(nil),  // 2: kaname.cloud.iam.v1.UpdateServiceAccountMetadata
	(*DeleteServiceAccountMetadata)(nil),  // 3: kaname.cloud.iam.v1.DeleteServiceAccountMetadata
	(*DisableServiceAccountMetadata)(nil), // 4: kaname.cloud.iam.v1.DisableServiceAccountMetadata
	(*EnableServiceAccountMetadata)(nil),  // 5: kaname.cloud.iam.v1.EnableServiceAccountMetadata
	nil,                                   // 6: kaname.cloud.iam.v1.ServiceAccount.LabelsEntry
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_service_account_proto_depIdxs = []int32{
	7, // 0: kaname.cloud.iam.v1.ServiceAccount.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: kaname.cloud.iam.v1.ServiceAccount.labels:type_name -> kaname.cloud.iam.v1.ServiceAccount.LabelsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_service_account_proto_init() }
func file_kaname_cloud_iam_v1_service_account_proto_init() {
	if File_kaname_cloud_iam_v1_service_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_service_account_proto_rawDesc), len(file_kaname_cloud_iam_v1_service_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kaname_cloud_iam_v1_service_account_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_service_account_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_service_account_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_service_account_proto = out.File
	file_kaname_cloud_iam_v1_service_account_proto_goTypes = nil
	file_kaname_cloud_iam_v1_service_account_proto_depIdxs = nil
}
