// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/session_revocation.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A SessionRevocation resource — fast-lookup row keyed by `token_jti`, used by
// api-gateway and CAEP drainer to know which active tokens have been revoked.
//
// PK = `token_jti` directly (lookup pattern is
// `WHERE token_jti = $1`, no other consumers, surrogate id is overhead).
// Each row TTLs at `ttl_expires_at` (default 30d); background cron prunes.
//
// Admin-only read access via `Internal*` API; no public surface.
//
// No `id` prefix (PK is raw `token_jti`).
type SessionRevocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT `jti` claim (RFC 7519). Format chosen by the issuer (UUIDv7).
	// Primary key.
	TokenJti string `protobuf:"bytes,1,opt,name=token_jti,json=tokenJti,proto3" json:"token_jti,omitempty"`
	// User whose session is revoked.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Revocation timestamp.
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// After this timestamp the row may be pruned (token would naturally expire).
	TtlExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ttl_expires_at,json=ttlExpiresAt,proto3" json:"ttl_expires_at,omitempty"`
	// Free-form reason (e.g. `user-logout`, `password-change`, `caep-event`,
	// `admin-revoke`). 1-128 chars.
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRevocation) Reset() {
	*x = SessionRevocation{}
	mi := &file_kaname_cloud_iam_v1_session_revocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRevocation) ProtoMessage() {}

func (x *SessionRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRevocation.ProtoReflect.Descriptor instead.
func (*SessionRevocation) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocation_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRevocation) GetTokenJti() string {
	if x != nil {
		return x.TokenJti
	}
	return ""
}

func (x *SessionRevocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionRevocation) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *SessionRevocation) GetTtlExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TtlExpiresAt
	}
	return nil
}

func (x *SessionRevocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kaname_cloud_iam_v1_session_revocation_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_session_revocation_proto_rawDesc = "" +
	"\n" +
	",kaname/cloud/iam/v1/session_revocation.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x11SessionRevocation\x12\x1b\n" +
	"\ttoken_jti\x18\x01 \x01(\tR\btokenJti\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12@\n" +
	"\x0ettl_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fttlExpiresAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_session_revocation_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_session_revocation_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_session_revocation_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_session_revocation_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_session_revocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_session_revocation_proto_rawDesc), len(file_kaname_cloud_iam_v1_session_revocation_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_session_revocation_proto_rawDescData
}

var file_kaname_cloud_iam_v1_session_revocation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kaname_cloud_iam_v1_session_revocation_proto_goTypes = []any{
	(*SessionRevocation)(nil),     // 0: kaname.cloud.iam.v1.SessionRevocation
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_kaname_cloud_iam_v1_session_revocation_proto_depIdxs = []int32{
	1, // 0: kaname.cloud.iam.v1.SessionRevocation.revoked_at:type_name -> google.protobuf.Timestamp
	1, // 1: kaname.cloud.iam.v1.SessionRevocation.ttl_expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_session_revocation_proto_init() }
func file_kaname_cloud_iam_v1_session_revocation_proto_init() {
	if File_kaname_cloud_iam_v1_session_revocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_session_revocation_proto_rawDesc), len(file_kaname_cloud_iam_v1_session_revocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kaname_cloud_iam_v1_session_revocation_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_session_revocation_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_session_revocation_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_session_revocation_proto = out.File
	file_kaname_cloud_iam_v1_session_revocation_proto_goTypes = nil
	file_kaname_cloud_iam_v1_session_revocation_proto_depIdxs = nil
}
