// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kaname/cloud/iam/v1/session_revocations_service.proto

package iamv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/api/v1"
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	operation "github.com/PRO-Robotech/corelib/api/kacho/cloud/operation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RevokeRequest — input to InternalSessionRevocationsService.Revoke.
type RevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT `jti` of the token being revoked. Required when revoking a single
	// token; may be empty when `revoke_all_user_tokens=true` is set (then the
	// RPC enumerates active tokens via Hydra introspection and revokes each
	// individually).
	TokenJti string `protobuf:"bytes,1,opt,name=token_jti,json=tokenJti,proto3" json:"token_jti,omitempty"`
	// User whose token is revoked. Required.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Free-form reason — see SessionRevocation.reason for the canonical
	// vocabulary (`user-logout`, `password-change`, `caep-event`,
	// `admin-revoke`, `back-channel-logout`, `force-logout`).
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// After this timestamp the revocation row may be pruned (defaults to
	// `now() + 30d`). Should be ≥ original token's `exp` claim so the cache
	// stays authoritative for the token's lifetime.
	TtlExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ttl_expires_at,json=ttlExpiresAt,proto3" json:"ttl_expires_at,omitempty"`
	// When true, kaname enumerates ALL active access tokens for the user
	// (Hydra introspection) and inserts a row per `jti`. Used by admin
	// ForceLogout and password-change flows.
	RevokeAllUserTokens bool `protobuf:"varint,5,opt,name=revoke_all_user_tokens,json=revokeAllUserTokens,proto3" json:"revoke_all_user_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRequest) GetTokenJti() string {
	if x != nil {
		return x.TokenJti
	}
	return ""
}

func (x *RevokeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeRequest) GetTtlExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TtlExpiresAt
	}
	return nil
}

func (x *RevokeRequest) GetRevokeAllUserTokens() bool {
	if x != nil {
		return x.RevokeAllUserTokens
	}
	return false
}

// RevokeMetadata — Operation.metadata payload.
type RevokeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of token_jti rows that were newly inserted (excludes idempotent
	// no-ops on conflict).
	RevokedCount int32 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	// User whose session(s) were revoked.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMetadata) Reset() {
	*x = RevokeMetadata{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMetadata) ProtoMessage() {}

func (x *RevokeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMetadata.ProtoReflect.Descriptor instead.
func (*RevokeMetadata) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeMetadata) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

func (x *RevokeMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// IsRevokedRequest — sync hot-path lookup.
type IsRevokedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT `jti` to look up.
	TokenJti      string `protobuf:"bytes,1,opt,name=token_jti,json=tokenJti,proto3" json:"token_jti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRevokedRequest) Reset() {
	*x = IsRevokedRequest{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRevokedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRevokedRequest) ProtoMessage() {}

func (x *IsRevokedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRevokedRequest.ProtoReflect.Descriptor instead.
func (*IsRevokedRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{2}
}

func (x *IsRevokedRequest) GetTokenJti() string {
	if x != nil {
		return x.TokenJti
	}
	return ""
}

// IsRevokedResponse — sync hot-path response.
type IsRevokedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a non-expired row exists in `session_revocations`.
	Revoked bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// When the revocation row was inserted.
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// Reason recorded at insertion (echo of SessionRevocation.reason).
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRevokedResponse) Reset() {
	*x = IsRevokedResponse{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRevokedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRevokedResponse) ProtoMessage() {}

func (x *IsRevokedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRevokedResponse.ProtoReflect.Descriptor instead.
func (*IsRevokedResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{3}
}

func (x *IsRevokedResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *IsRevokedResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *IsRevokedResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ListByUserRequest — admin/audit enumeration.
type ListByUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User whose revocations to list.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Page size (default 100, max 1000).
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByUserRequest) Reset() {
	*x = ListByUserRequest{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserRequest) ProtoMessage() {}

func (x *ListByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserRequest.ProtoReflect.Descriptor instead.
func (*ListByUserRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListByUserRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListByUserRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListByUserResponse — admin/audit page.
type ListByUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active revocation rows for the user (not yet pruned).
	Revocations []*SessionRevocation `protobuf:"bytes,1,rep,name=revocations,proto3" json:"revocations,omitempty"`
	// Continuation token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByUserResponse) Reset() {
	*x = ListByUserResponse{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserResponse) ProtoMessage() {}

func (x *ListByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserResponse.ProtoReflect.Descriptor instead.
func (*ListByUserResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListByUserResponse) GetRevocations() []*SessionRevocation {
	if x != nil {
		return x.Revocations
	}
	return nil
}

func (x *ListByUserResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// SessionCutoffOfRequest — вопрос про СУБЪЕКТА, а не про удостоверение.
type SessionCutoffOfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Человек, про сессии которого спрашивают (`users.id`).
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCutoffOfRequest) Reset() {
	*x = SessionCutoffOfRequest{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCutoffOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCutoffOfRequest) ProtoMessage() {}

func (x *SessionCutoffOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCutoffOfRequest.ProtoReflect.Descriptor instead.
func (*SessionCutoffOfRequest) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{6}
}

func (x *SessionCutoffOfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// SessionCutoffOfResponse — отсечка субъекта.
type SessionCutoffOfResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Есть ли отсечка вообще. ОТДЕЛЬНОЕ поле, а не «нулевая отметка времени»:
	// пустое обязано означать пусто, и вызывающий, читающий нулевой момент как
	// «отозвано всё», закрылся бы на каждом человеке, которого никто не отзывал.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Момент отсечки. Сессия, аутентифицировавшаяся В ЭТОТ момент или раньше,
	// недействительна; аутентифицировавшаяся позже — законна.
	RevokeBefore *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoke_before,json=revokeBefore,proto3" json:"revoke_before,omitempty"`
	// Причина, записанная вместе с отсечкой. Для диагностики оператору; решение
	// принимается по паре (found, revoke_before), а не по разбору этой строки.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCutoffOfResponse) Reset() {
	*x = SessionCutoffOfResponse{}
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCutoffOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCutoffOfResponse) ProtoMessage() {}

func (x *SessionCutoffOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCutoffOfResponse.ProtoReflect.Descriptor instead.
func (*SessionCutoffOfResponse) Descriptor() ([]byte, []int) {
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP(), []int{7}
}

func (x *SessionCutoffOfResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SessionCutoffOfResponse) GetRevokeBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokeBefore
	}
	return nil
}

func (x *SessionCutoffOfResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kaname_cloud_iam_v1_session_revocations_service_proto protoreflect.FileDescriptor

const file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDesc = "" +
	"\n" +
	"5kaname/cloud/iam/v1/session_revocations_service.proto\x12\x13kaname.cloud.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ecorelib/api/v1/operation.proto\x1a,kaname/cloud/iam/v1/session_revocation.proto\x1a%kacho/cloud/operation/operation.proto\x1a$corelib/authz/v1/authz_options.proto\"\xd4\x01\n" +
	"\rRevokeRequest\x12\x1b\n" +
	"\ttoken_jti\x18\x01 \x01(\tR\btokenJti\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12@\n" +
	"\x0ettl_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fttlExpiresAt\x123\n" +
	"\x16revoke_all_user_tokens\x18\x05 \x01(\bR\x13revokeAllUserTokens\"N\n" +
	"\x0eRevokeMetadata\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x10IsRevokedRequest\x12\x1b\n" +
	"\ttoken_jti\x18\x01 \x01(\tR\btokenJti\"\x80\x01\n" +
	"\x11IsRevokedResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x129\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"h\n" +
	"\x11ListByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x12ListByUserResponse\x12H\n" +
	"\vrevocations\x18\x01 \x03(\v2&.kaname.cloud.iam.v1.SessionRevocationR\vrevocations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"1\n" +
	"\x16SessionCutoffOfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x88\x01\n" +
	"\x17SessionCutoffOfResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12?\n" +
	"\rrevoke_before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\frevokeBefore\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\x89\x05\n" +
	"!InternalSessionRevocationsService\x12\x98\x01\n" +
	"\x06Revoke\x12\".kaname.cloud.iam.v1.RevokeRequest\x1a .kacho.cloud.operation.Operation\"H\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x11INTERNAL_LISTENER\xb2\xd2*#\n" +
	"\x0eRevokeMetadata\x12\x11SessionRevocation\x12}\n" +
	"\tIsRevoked\x12%.kaname.cloud.iam.v1.IsRevokedRequest\x1a&.kaname.cloud.iam.v1.IsRevokedResponse\"!\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x11INTERNAL_LISTENER\x12\xb7\x01\n" +
	"\n" +
	"ListByUser\x12&.kaname.cloud.iam.v1.ListByUserRequest\x1a'.kaname.cloud.iam.v1.ListByUserResponse\"X\x8a\xb5\x18\"iam.session_revocations.listByUser\x92\xb5\x18\x0esession_reader\x9a\xb5\x18\x13\n" +
	"\biam_user\x12\auser_id\xa2\xb5\x18\x011\xa8\xb5\x18\x01\x12\x8f\x01\n" +
	"\x0fSessionCutoffOf\x12+.kaname.cloud.iam.v1.SessionCutoffOfRequest\x1a,.kaname.cloud.iam.v1.SessionCutoffOfResponse\"!\x8a\xb5\x18\b<exempt>\xba\xb5\x18\x11INTERNAL_LISTENERBBZ@github.com/PRO-Robotech/kaname/pkg/api/kaname/cloud/iam/v1;iamv1b\x06proto3"

var (
	file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescOnce sync.Once
	file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescData []byte
)

func file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescGZIP() []byte {
	file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescOnce.Do(func() {
		file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDesc)))
	})
	return file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDescData
}

var file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kaname_cloud_iam_v1_session_revocations_service_proto_goTypes = []any{
	(*RevokeRequest)(nil),           // 0: kaname.cloud.iam.v1.RevokeRequest
	(*RevokeMetadata)(nil),          // 1: kaname.cloud.iam.v1.RevokeMetadata
	(*IsRevokedRequest)(nil),        // 2: kaname.cloud.iam.v1.IsRevokedRequest
	(*IsRevokedResponse)(nil),       // 3: kaname.cloud.iam.v1.IsRevokedResponse
	(*ListByUserRequest)(nil),       // 4: kaname.cloud.iam.v1.ListByUserRequest
	(*ListByUserResponse)(nil),      // 5: kaname.cloud.iam.v1.ListByUserResponse
	(*SessionCutoffOfRequest)(nil),  // 6: kaname.cloud.iam.v1.SessionCutoffOfRequest
	(*SessionCutoffOfResponse)(nil), // 7: kaname.cloud.iam.v1.SessionCutoffOfResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(*SessionRevocation)(nil),       // 9: kaname.cloud.iam.v1.SessionRevocation
	(*operation.Operation)(nil),     // 10: kacho.cloud.operation.Operation
}
var file_kaname_cloud_iam_v1_session_revocations_service_proto_depIdxs = []int32{
	8,  // 0: kaname.cloud.iam.v1.RevokeRequest.ttl_expires_at:type_name -> google.protobuf.Timestamp
	8,  // 1: kaname.cloud.iam.v1.IsRevokedResponse.revoked_at:type_name -> google.protobuf.Timestamp
	9,  // 2: kaname.cloud.iam.v1.ListByUserResponse.revocations:type_name -> kaname.cloud.iam.v1.SessionRevocation
	8,  // 3: kaname.cloud.iam.v1.SessionCutoffOfResponse.revoke_before:type_name -> google.protobuf.Timestamp
	0,  // 4: kaname.cloud.iam.v1.InternalSessionRevocationsService.Revoke:input_type -> kaname.cloud.iam.v1.RevokeRequest
	2,  // 5: kaname.cloud.iam.v1.InternalSessionRevocationsService.IsRevoked:input_type -> kaname.cloud.iam.v1.IsRevokedRequest
	4,  // 6: kaname.cloud.iam.v1.InternalSessionRevocationsService.ListByUser:input_type -> kaname.cloud.iam.v1.ListByUserRequest
	6,  // 7: kaname.cloud.iam.v1.InternalSessionRevocationsService.SessionCutoffOf:input_type -> kaname.cloud.iam.v1.SessionCutoffOfRequest
	10, // 8: kaname.cloud.iam.v1.InternalSessionRevocationsService.Revoke:output_type -> kacho.cloud.operation.Operation
	3,  // 9: kaname.cloud.iam.v1.InternalSessionRevocationsService.IsRevoked:output_type -> kaname.cloud.iam.v1.IsRevokedResponse
	5,  // 10: kaname.cloud.iam.v1.InternalSessionRevocationsService.ListByUser:output_type -> kaname.cloud.iam.v1.ListByUserResponse
	7,  // 11: kaname.cloud.iam.v1.InternalSessionRevocationsService.SessionCutoffOf:output_type -> kaname.cloud.iam.v1.SessionCutoffOfResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kaname_cloud_iam_v1_session_revocations_service_proto_init() }
func file_kaname_cloud_iam_v1_session_revocations_service_proto_init() {
	if File_kaname_cloud_iam_v1_session_revocations_service_proto != nil {
		return
	}
	file_kaname_cloud_iam_v1_session_revocation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDesc), len(file_kaname_cloud_iam_v1_session_revocations_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kaname_cloud_iam_v1_session_revocations_service_proto_goTypes,
		DependencyIndexes: file_kaname_cloud_iam_v1_session_revocations_service_proto_depIdxs,
		MessageInfos:      file_kaname_cloud_iam_v1_session_revocations_service_proto_msgTypes,
	}.Build()
	File_kaname_cloud_iam_v1_session_revocations_service_proto = out.File
	file_kaname_cloud_iam_v1_session_revocations_service_proto_goTypes = nil
	file_kaname_cloud_iam_v1_session_revocations_service_proto_depIdxs = nil
}
